// Code generated by ent, DO NOT EDIT.

package partnerconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.smartbet.am/golang/notification/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldTenantID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldEnabled, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLTE(FieldUpdateTime, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldLTE(FieldTenantID, v))
}

// EmailProvidersIsNil applies the IsNil predicate on the "email_providers" field.
func EmailProvidersIsNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIsNull(FieldEmailProviders))
}

// EmailProvidersNotNil applies the NotNil predicate on the "email_providers" field.
func EmailProvidersNotNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotNull(FieldEmailProviders))
}

// SmsProvidersIsNil applies the IsNil predicate on the "sms_providers" field.
func SmsProvidersIsNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIsNull(FieldSmsProviders))
}

// SmsProvidersNotNil applies the NotNil predicate on the "sms_providers" field.
func SmsProvidersNotNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotNull(FieldSmsProviders))
}

// PushProvidersIsNil applies the IsNil predicate on the "push_providers" field.
func PushProvidersIsNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIsNull(FieldPushProviders))
}

// PushProvidersNotNil applies the NotNil predicate on the "push_providers" field.
func PushProvidersNotNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotNull(FieldPushProviders))
}

// BatchConfigIsNil applies the IsNil predicate on the "batch_config" field.
func BatchConfigIsNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIsNull(FieldBatchConfig))
}

// BatchConfigNotNil applies the NotNil predicate on the "batch_config" field.
func BatchConfigNotNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotNull(FieldBatchConfig))
}

// RateLimitsIsNil applies the IsNil predicate on the "rate_limits" field.
func RateLimitsIsNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldIsNull(FieldRateLimits))
}

// RateLimitsNotNil applies the NotNil predicate on the "rate_limits" field.
func RateLimitsNotNil() predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNotNull(FieldRateLimits))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PartnerConfig) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PartnerConfig) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PartnerConfig) predicate.PartnerConfig {
	return predicate.PartnerConfig(sql.NotPredicates(p))
}
