// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: notification/notification.proto

package notification

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NotificationService service

func NewNotificationServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NotificationService service

type NotificationService interface {
	Sms(ctx context.Context, in *SmsRequest, opts ...client.CallOption) (*SmsResponse, error)
	Email(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*EmailResponse, error)
	Notification(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*PushResponse, error)
	Retry(ctx context.Context, in *RetryRequest, opts ...client.CallOption) (*RetryResponse, error)
}

type notificationService struct {
	c    client.Client
	name string
}

func NewNotificationService(name string, c client.Client) NotificationService {
	return &notificationService{
		c:    c,
		name: name,
	}
}

func (c *notificationService) Sms(ctx context.Context, in *SmsRequest, opts ...client.CallOption) (*SmsResponse, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Sms", in)
	out := new(SmsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Email(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*EmailResponse, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Email", in)
	out := new(EmailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Notification(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*PushResponse, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Notification", in)
	out := new(PushResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Retry(ctx context.Context, in *RetryRequest, opts ...client.CallOption) (*RetryResponse, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Retry", in)
	out := new(RetryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NotificationService service

type NotificationServiceHandler interface {
	Sms(context.Context, *SmsRequest, *SmsResponse) error
	Email(context.Context, *EmailRequest, *EmailResponse) error
	Notification(context.Context, *PushRequest, *PushResponse) error
	Retry(context.Context, *RetryRequest, *RetryResponse) error
}

func RegisterNotificationServiceHandler(s server.Server, hdlr NotificationServiceHandler, opts ...server.HandlerOption) error {
	type notificationService interface {
		Sms(ctx context.Context, in *SmsRequest, out *SmsResponse) error
		Email(ctx context.Context, in *EmailRequest, out *EmailResponse) error
		Notification(ctx context.Context, in *PushRequest, out *PushResponse) error
		Retry(ctx context.Context, in *RetryRequest, out *RetryResponse) error
	}
	type NotificationService struct {
		notificationService
	}
	h := &notificationServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NotificationService{h}, opts...))
}

type notificationServiceHandler struct {
	NotificationServiceHandler
}

func (h *notificationServiceHandler) Sms(ctx context.Context, in *SmsRequest, out *SmsResponse) error {
	return h.NotificationServiceHandler.Sms(ctx, in, out)
}

func (h *notificationServiceHandler) Email(ctx context.Context, in *EmailRequest, out *EmailResponse) error {
	return h.NotificationServiceHandler.Email(ctx, in, out)
}

func (h *notificationServiceHandler) Notification(ctx context.Context, in *PushRequest, out *PushResponse) error {
	return h.NotificationServiceHandler.Notification(ctx, in, out)
}

func (h *notificationServiceHandler) Retry(ctx context.Context, in *RetryRequest, out *RetryResponse) error {
	return h.NotificationServiceHandler.Retry(ctx, in, out)
}
