// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: notification/notification.proto

package notification

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NotificationService service

func NewNotificationServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NotificationService service

type NotificationService interface {
	Sms(ctx context.Context, in *SmsRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	Email(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	Notification(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	Retry(ctx context.Context, in *NotificationInfo, opts ...client.CallOption) (*emptypb.Empty, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	CancelPrefix(ctx context.Context, in *CancelPrefixRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...client.CallOption) (*NotificationList, error)
}

type notificationService struct {
	c    client.Client
	name string
}

func NewNotificationService(name string, c client.Client) NotificationService {
	return &notificationService{
		c:    c,
		name: name,
	}
}

func (c *notificationService) Sms(ctx context.Context, in *SmsRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Sms", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Email(ctx context.Context, in *EmailRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Email", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Notification(ctx context.Context, in *PushRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Notification", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Retry(ctx context.Context, in *NotificationInfo, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Retry", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.Cancel", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) CancelPrefix(ctx context.Context, in *CancelPrefixRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "NotificationService.CancelPrefix", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationService) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...client.CallOption) (*NotificationList, error) {
	req := c.c.NewRequest(c.name, "NotificationService.ListNotifications", in)
	out := new(NotificationList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NotificationService service

type NotificationServiceHandler interface {
	Sms(context.Context, *SmsRequest, *emptypb.Empty) error
	Email(context.Context, *EmailRequest, *emptypb.Empty) error
	Notification(context.Context, *PushRequest, *emptypb.Empty) error
	Retry(context.Context, *NotificationInfo, *emptypb.Empty) error
	Cancel(context.Context, *CancelRequest, *emptypb.Empty) error
	CancelPrefix(context.Context, *CancelPrefixRequest, *emptypb.Empty) error
	ListNotifications(context.Context, *ListNotificationsRequest, *NotificationList) error
}

func RegisterNotificationServiceHandler(s server.Server, hdlr NotificationServiceHandler, opts ...server.HandlerOption) error {
	type notificationService interface {
		Sms(ctx context.Context, in *SmsRequest, out *emptypb.Empty) error
		Email(ctx context.Context, in *EmailRequest, out *emptypb.Empty) error
		Notification(ctx context.Context, in *PushRequest, out *emptypb.Empty) error
		Retry(ctx context.Context, in *NotificationInfo, out *emptypb.Empty) error
		Cancel(ctx context.Context, in *CancelRequest, out *emptypb.Empty) error
		CancelPrefix(ctx context.Context, in *CancelPrefixRequest, out *emptypb.Empty) error
		ListNotifications(ctx context.Context, in *ListNotificationsRequest, out *NotificationList) error
	}
	type NotificationService struct {
		notificationService
	}
	h := &notificationServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NotificationService{h}, opts...))
}

type notificationServiceHandler struct {
	NotificationServiceHandler
}

func (h *notificationServiceHandler) Sms(ctx context.Context, in *SmsRequest, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.Sms(ctx, in, out)
}

func (h *notificationServiceHandler) Email(ctx context.Context, in *EmailRequest, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.Email(ctx, in, out)
}

func (h *notificationServiceHandler) Notification(ctx context.Context, in *PushRequest, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.Notification(ctx, in, out)
}

func (h *notificationServiceHandler) Retry(ctx context.Context, in *NotificationInfo, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.Retry(ctx, in, out)
}

func (h *notificationServiceHandler) Cancel(ctx context.Context, in *CancelRequest, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.Cancel(ctx, in, out)
}

func (h *notificationServiceHandler) CancelPrefix(ctx context.Context, in *CancelPrefixRequest, out *emptypb.Empty) error {
	return h.NotificationServiceHandler.CancelPrefix(ctx, in, out)
}

func (h *notificationServiceHandler) ListNotifications(ctx context.Context, in *ListNotificationsRequest, out *NotificationList) error {
	return h.NotificationServiceHandler.ListNotifications(ctx, in, out)
}
