// Code generated by entc, DO NOT EDIT.

package notification

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the notification type in the database.
	Label = "notification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldHeadline holds the string denoting the headline field in the database.
	FieldHeadline = "headline"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldScheduleTs holds the string denoting the schedule_ts field in the database.
	FieldScheduleTs = "schedule_ts"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// Table holds the table name of the notification in the database.
	Table = "notifications"
)

// Columns holds all SQL columns for notification fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldBody,
	FieldHeadline,
	FieldName,
	FieldAddress,
	FieldRequestID,
	FieldScheduleTs,
	FieldType,
	FieldStatus,
	FieldMeta,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeSMS   Type = "SMS"
	TypeEMAIL Type = "EMAIL"
	TypePUSH  Type = "PUSH"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeSMS, TypeEMAIL, TypePUSH:
		return nil
	default:
		return fmt.Errorf("notification: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusACTIVE    Status = "ACTIVE"
	StatusCOMPLETED Status = "COMPLETED"
	StatusCANCEL    Status = "CANCEL"
	StatusPENDING   Status = "PENDING"
	StatusFAILED    Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusACTIVE, StatusCOMPLETED, StatusCANCEL, StatusPENDING, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("notification: invalid enum value for status field: %q", s)
	}
}
