// Code generated by ent, DO NOT EDIT.

package notification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.smartbet.am/golang/notification/ent/predicate"
	"gitlab.smartbet.am/golang/notification/types"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldUpdateTime, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldBody, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldTenantID, v))
}

// Headline applies equality check predicate on the "headline" field. It's identical to HeadlineEQ.
func Headline(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldHeadline, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldName, v))
}

// From applies equality check predicate on the "from" field. It's identical to FromEQ.
func From(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldFrom, v))
}

// ReplyTo applies equality check predicate on the "reply_to" field. It's identical to ReplyToEQ.
func ReplyTo(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldReplyTo, v))
}

// Tag applies equality check predicate on the "tag" field. It's identical to TagEQ.
func Tag(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldTag, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldAddress, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldRequestID, v))
}

// ScheduleTs applies equality check predicate on the "schedule_ts" field. It's identical to ScheduleTsEQ.
func ScheduleTs(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldScheduleTs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldErrorMessage, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldUpdateTime, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldBody, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldTenantID, v))
}

// HeadlineEQ applies the EQ predicate on the "headline" field.
func HeadlineEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldHeadline, v))
}

// HeadlineNEQ applies the NEQ predicate on the "headline" field.
func HeadlineNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldHeadline, v))
}

// HeadlineIn applies the In predicate on the "headline" field.
func HeadlineIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldHeadline, vs...))
}

// HeadlineNotIn applies the NotIn predicate on the "headline" field.
func HeadlineNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldHeadline, vs...))
}

// HeadlineGT applies the GT predicate on the "headline" field.
func HeadlineGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldHeadline, v))
}

// HeadlineGTE applies the GTE predicate on the "headline" field.
func HeadlineGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldHeadline, v))
}

// HeadlineLT applies the LT predicate on the "headline" field.
func HeadlineLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldHeadline, v))
}

// HeadlineLTE applies the LTE predicate on the "headline" field.
func HeadlineLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldHeadline, v))
}

// HeadlineContains applies the Contains predicate on the "headline" field.
func HeadlineContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldHeadline, v))
}

// HeadlineHasPrefix applies the HasPrefix predicate on the "headline" field.
func HeadlineHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldHeadline, v))
}

// HeadlineHasSuffix applies the HasSuffix predicate on the "headline" field.
func HeadlineHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldHeadline, v))
}

// HeadlineIsNil applies the IsNil predicate on the "headline" field.
func HeadlineIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldHeadline))
}

// HeadlineNotNil applies the NotNil predicate on the "headline" field.
func HeadlineNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldHeadline))
}

// HeadlineEqualFold applies the EqualFold predicate on the "headline" field.
func HeadlineEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldHeadline, v))
}

// HeadlineContainsFold applies the ContainsFold predicate on the "headline" field.
func HeadlineContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldHeadline, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldName, v))
}

// FromEQ applies the EQ predicate on the "from" field.
func FromEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldFrom, v))
}

// FromNEQ applies the NEQ predicate on the "from" field.
func FromNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldFrom, v))
}

// FromIn applies the In predicate on the "from" field.
func FromIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldFrom, vs...))
}

// FromNotIn applies the NotIn predicate on the "from" field.
func FromNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldFrom, vs...))
}

// FromGT applies the GT predicate on the "from" field.
func FromGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldFrom, v))
}

// FromGTE applies the GTE predicate on the "from" field.
func FromGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldFrom, v))
}

// FromLT applies the LT predicate on the "from" field.
func FromLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldFrom, v))
}

// FromLTE applies the LTE predicate on the "from" field.
func FromLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldFrom, v))
}

// FromContains applies the Contains predicate on the "from" field.
func FromContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldFrom, v))
}

// FromHasPrefix applies the HasPrefix predicate on the "from" field.
func FromHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldFrom, v))
}

// FromHasSuffix applies the HasSuffix predicate on the "from" field.
func FromHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldFrom, v))
}

// FromIsNil applies the IsNil predicate on the "from" field.
func FromIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldFrom))
}

// FromNotNil applies the NotNil predicate on the "from" field.
func FromNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldFrom))
}

// FromEqualFold applies the EqualFold predicate on the "from" field.
func FromEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldFrom, v))
}

// FromContainsFold applies the ContainsFold predicate on the "from" field.
func FromContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldFrom, v))
}

// ReplyToEQ applies the EQ predicate on the "reply_to" field.
func ReplyToEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldReplyTo, v))
}

// ReplyToNEQ applies the NEQ predicate on the "reply_to" field.
func ReplyToNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldReplyTo, v))
}

// ReplyToIn applies the In predicate on the "reply_to" field.
func ReplyToIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldReplyTo, vs...))
}

// ReplyToNotIn applies the NotIn predicate on the "reply_to" field.
func ReplyToNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldReplyTo, vs...))
}

// ReplyToGT applies the GT predicate on the "reply_to" field.
func ReplyToGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldReplyTo, v))
}

// ReplyToGTE applies the GTE predicate on the "reply_to" field.
func ReplyToGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldReplyTo, v))
}

// ReplyToLT applies the LT predicate on the "reply_to" field.
func ReplyToLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldReplyTo, v))
}

// ReplyToLTE applies the LTE predicate on the "reply_to" field.
func ReplyToLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldReplyTo, v))
}

// ReplyToContains applies the Contains predicate on the "reply_to" field.
func ReplyToContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldReplyTo, v))
}

// ReplyToHasPrefix applies the HasPrefix predicate on the "reply_to" field.
func ReplyToHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldReplyTo, v))
}

// ReplyToHasSuffix applies the HasSuffix predicate on the "reply_to" field.
func ReplyToHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldReplyTo, v))
}

// ReplyToIsNil applies the IsNil predicate on the "reply_to" field.
func ReplyToIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldReplyTo))
}

// ReplyToNotNil applies the NotNil predicate on the "reply_to" field.
func ReplyToNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldReplyTo))
}

// ReplyToEqualFold applies the EqualFold predicate on the "reply_to" field.
func ReplyToEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldReplyTo, v))
}

// ReplyToContainsFold applies the ContainsFold predicate on the "reply_to" field.
func ReplyToContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldReplyTo, v))
}

// TagEQ applies the EQ predicate on the "tag" field.
func TagEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldTag, v))
}

// TagNEQ applies the NEQ predicate on the "tag" field.
func TagNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldTag, v))
}

// TagIn applies the In predicate on the "tag" field.
func TagIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldTag, vs...))
}

// TagNotIn applies the NotIn predicate on the "tag" field.
func TagNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldTag, vs...))
}

// TagGT applies the GT predicate on the "tag" field.
func TagGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldTag, v))
}

// TagGTE applies the GTE predicate on the "tag" field.
func TagGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldTag, v))
}

// TagLT applies the LT predicate on the "tag" field.
func TagLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldTag, v))
}

// TagLTE applies the LTE predicate on the "tag" field.
func TagLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldTag, v))
}

// TagContains applies the Contains predicate on the "tag" field.
func TagContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldTag, v))
}

// TagHasPrefix applies the HasPrefix predicate on the "tag" field.
func TagHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldTag, v))
}

// TagHasSuffix applies the HasSuffix predicate on the "tag" field.
func TagHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldTag, v))
}

// TagIsNil applies the IsNil predicate on the "tag" field.
func TagIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldTag))
}

// TagNotNil applies the NotNil predicate on the "tag" field.
func TagNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldTag))
}

// TagEqualFold applies the EqualFold predicate on the "tag" field.
func TagEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldTag, v))
}

// TagContainsFold applies the ContainsFold predicate on the "tag" field.
func TagContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldTag, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v types.Address) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v types.Address) predicate.Notification {
	vc := string(v)
	return predicate.Notification(sql.FieldContains(FieldAddress, vc))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v types.Address) predicate.Notification {
	vc := string(v)
	return predicate.Notification(sql.FieldHasPrefix(FieldAddress, vc))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v types.Address) predicate.Notification {
	vc := string(v)
	return predicate.Notification(sql.FieldHasSuffix(FieldAddress, vc))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v types.Address) predicate.Notification {
	vc := string(v)
	return predicate.Notification(sql.FieldEqualFold(FieldAddress, vc))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v types.Address) predicate.Notification {
	vc := string(v)
	return predicate.Notification(sql.FieldContainsFold(FieldAddress, vc))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldRequestID, v))
}

// ScheduleTsEQ applies the EQ predicate on the "schedule_ts" field.
func ScheduleTsEQ(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldScheduleTs, v))
}

// ScheduleTsNEQ applies the NEQ predicate on the "schedule_ts" field.
func ScheduleTsNEQ(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldScheduleTs, v))
}

// ScheduleTsIn applies the In predicate on the "schedule_ts" field.
func ScheduleTsIn(vs ...int64) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldScheduleTs, vs...))
}

// ScheduleTsNotIn applies the NotIn predicate on the "schedule_ts" field.
func ScheduleTsNotIn(vs ...int64) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldScheduleTs, vs...))
}

// ScheduleTsGT applies the GT predicate on the "schedule_ts" field.
func ScheduleTsGT(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldScheduleTs, v))
}

// ScheduleTsGTE applies the GTE predicate on the "schedule_ts" field.
func ScheduleTsGTE(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldScheduleTs, v))
}

// ScheduleTsLT applies the LT predicate on the "schedule_ts" field.
func ScheduleTsLT(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldScheduleTs, v))
}

// ScheduleTsLTE applies the LTE predicate on the "schedule_ts" field.
func ScheduleTsLTE(v int64) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldScheduleTs, v))
}

// ScheduleTsIsNil applies the IsNil predicate on the "schedule_ts" field.
func ScheduleTsIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldScheduleTs))
}

// ScheduleTsNotNil applies the NotNil predicate on the "schedule_ts" field.
func ScheduleTsNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldScheduleTs))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldStatus, vs...))
}

// MetaIsNil applies the IsNil predicate on the "meta" field.
func MetaIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldMeta))
}

// MetaNotNil applies the NotNil predicate on the "meta" field.
func MetaNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldMeta))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Notification {
	return predicate.Notification(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Notification {
	return predicate.Notification(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Notification {
	return predicate.Notification(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Notification {
	return predicate.Notification(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Notification {
	return predicate.Notification(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Notification {
	return predicate.Notification(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Notification {
	return predicate.Notification(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Notification) predicate.Notification {
	return predicate.Notification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Notification) predicate.Notification {
	return predicate.Notification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Notification) predicate.Notification {
	return predicate.Notification(sql.NotPredicates(p))
}
