// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "headline", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "from", Type: field.TypeString, Nullable: true},
		{Name: "reply_to", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Size: 2147483647},
		{Name: "request_id", Type: field.TypeString, Nullable: true},
		{Name: "schedule_ts", Type: field.TypeInt64, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SMS", "EMAIL", "PUSH"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "COMPLETED", "CANCEL", "PENDING", "FAILED"}, Default: "PENDING"},
		{Name: "meta", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_request_id",
				Unique:  true,
				Columns: []*schema.Column{NotificationsColumns[9]},
			},
			{
				Name:    "notification_schedule_ts_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[10], NotificationsColumns[12]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotificationsTable,
	}
)

func init() {
}
