// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "headline", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "from", Type: field.TypeString, Nullable: true},
		{Name: "reply_to", Type: field.TypeString, Nullable: true},
		{Name: "tag", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Size: 2147483647},
		{Name: "request_id", Type: field.TypeString, Unique: true},
		{Name: "schedule_ts", Type: field.TypeInt64, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SMS", "EMAIL", "PUSH"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "COMPLETED", "CANCEL", "PENDING", "FAILED"}, Default: "PENDING"},
		{Name: "meta", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "batch_id", Type: field.TypeString, Nullable: true},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_request_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[11]},
				Annotation: &entsql.IndexAnnotation{
					Prefix: 20,
				},
			},
			{
				Name:    "notification_schedule_ts_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[12], NotificationsColumns[14]},
			},
			{
				Name:    "notification_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[4], NotificationsColumns[14]},
			},
			{
				Name:    "notification_batch_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[17]},
			},
			{
				Name:    "notification_type_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[13], NotificationsColumns[14]},
			},
		},
	}
	// PartnerConfigsColumns holds the columns for the "partner_configs" table.
	PartnerConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64, Unique: true},
		{Name: "email_providers", Type: field.TypeJSON, Nullable: true},
		{Name: "sms_providers", Type: field.TypeJSON, Nullable: true},
		{Name: "push_providers", Type: field.TypeJSON, Nullable: true},
		{Name: "batch_config", Type: field.TypeJSON, Nullable: true},
		{Name: "rate_limits", Type: field.TypeJSON, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// PartnerConfigsTable holds the schema information for the "partner_configs" table.
	PartnerConfigsTable = &schema.Table{
		Name:       "partner_configs",
		Columns:    PartnerConfigsColumns,
		PrimaryKey: []*schema.Column{PartnerConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "partnerconfig_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PartnerConfigsColumns[3]},
			},
			{
				Name:    "partnerconfig_enabled",
				Unique:  false,
				Columns: []*schema.Column{PartnerConfigsColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotificationsTable,
		PartnerConfigsTable,
	}
)

func init() {
}
