// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/notification"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/predicate"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/schema"
	"gitlab.com/healthcare-integration/golang/notification-service/types"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeNotification = "Notification"
)

// NotificationMutation represents an operation that mutates the Notification nodes in the graph.
type NotificationMutation struct {
	config
	op             Op
	typ            string
	id             *int
	create_time    *time.Time
	update_time    *time.Time
	body           *string
	headline       *string
	name           *string
	from           *string
	reply_to       *string
	tag            *string
	address        *types.Address
	request_id     *string
	schedule_ts    *int64
	addschedule_ts *int64
	_type          *notification.Type
	status         *notification.Status
	meta           **schema.NotificationMeta
	error_message  *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*Notification, error)
	predicates     []predicate.Notification
}

var _ ent.Mutation = (*NotificationMutation)(nil)

// notificationOption allows management of the mutation configuration using functional options.
type notificationOption func(*NotificationMutation)

// newNotificationMutation creates new mutation for the Notification entity.
func newNotificationMutation(c config, op Op, opts ...notificationOption) *NotificationMutation {
	m := &NotificationMutation{
		config:        c,
		op:            op,
		typ:           TypeNotification,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotificationID sets the ID field of the mutation.
func withNotificationID(id int) notificationOption {
	return func(m *NotificationMutation) {
		var (
			err   error
			once  sync.Once
			value *Notification
		)
		m.oldValue = func(ctx context.Context) (*Notification, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Notification.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotification sets the old Notification of the mutation.
func withNotification(node *Notification) notificationOption {
	return func(m *NotificationMutation) {
		m.oldValue = func(context.Context) (*Notification, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotificationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotificationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotificationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotificationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Notification.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *NotificationMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *NotificationMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *NotificationMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *NotificationMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *NotificationMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *NotificationMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetBody sets the "body" field.
func (m *NotificationMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *NotificationMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ResetBody resets all changes to the "body" field.
func (m *NotificationMutation) ResetBody() {
	m.body = nil
}

// SetHeadline sets the "headline" field.
func (m *NotificationMutation) SetHeadline(s string) {
	m.headline = &s
}

// Headline returns the value of the "headline" field in the mutation.
func (m *NotificationMutation) Headline() (r string, exists bool) {
	v := m.headline
	if v == nil {
		return
	}
	return *v, true
}

// OldHeadline returns the old "headline" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldHeadline(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeadline is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeadline requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeadline: %w", err)
	}
	return oldValue.Headline, nil
}

// ClearHeadline clears the value of the "headline" field.
func (m *NotificationMutation) ClearHeadline() {
	m.headline = nil
	m.clearedFields[notification.FieldHeadline] = struct{}{}
}

// HeadlineCleared returns if the "headline" field was cleared in this mutation.
func (m *NotificationMutation) HeadlineCleared() bool {
	_, ok := m.clearedFields[notification.FieldHeadline]
	return ok
}

// ResetHeadline resets all changes to the "headline" field.
func (m *NotificationMutation) ResetHeadline() {
	m.headline = nil
	delete(m.clearedFields, notification.FieldHeadline)
}

// SetName sets the "name" field.
func (m *NotificationMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *NotificationMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *NotificationMutation) ClearName() {
	m.name = nil
	m.clearedFields[notification.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *NotificationMutation) NameCleared() bool {
	_, ok := m.clearedFields[notification.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *NotificationMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, notification.FieldName)
}

// SetFrom sets the "from" field.
func (m *NotificationMutation) SetFrom(s string) {
	m.from = &s
}

// From returns the value of the "from" field in the mutation.
func (m *NotificationMutation) From() (r string, exists bool) {
	v := m.from
	if v == nil {
		return
	}
	return *v, true
}

// OldFrom returns the old "from" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldFrom(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFrom is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFrom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFrom: %w", err)
	}
	return oldValue.From, nil
}

// ClearFrom clears the value of the "from" field.
func (m *NotificationMutation) ClearFrom() {
	m.from = nil
	m.clearedFields[notification.FieldFrom] = struct{}{}
}

// FromCleared returns if the "from" field was cleared in this mutation.
func (m *NotificationMutation) FromCleared() bool {
	_, ok := m.clearedFields[notification.FieldFrom]
	return ok
}

// ResetFrom resets all changes to the "from" field.
func (m *NotificationMutation) ResetFrom() {
	m.from = nil
	delete(m.clearedFields, notification.FieldFrom)
}

// SetReplyTo sets the "reply_to" field.
func (m *NotificationMutation) SetReplyTo(s string) {
	m.reply_to = &s
}

// ReplyTo returns the value of the "reply_to" field in the mutation.
func (m *NotificationMutation) ReplyTo() (r string, exists bool) {
	v := m.reply_to
	if v == nil {
		return
	}
	return *v, true
}

// OldReplyTo returns the old "reply_to" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldReplyTo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReplyTo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReplyTo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReplyTo: %w", err)
	}
	return oldValue.ReplyTo, nil
}

// ClearReplyTo clears the value of the "reply_to" field.
func (m *NotificationMutation) ClearReplyTo() {
	m.reply_to = nil
	m.clearedFields[notification.FieldReplyTo] = struct{}{}
}

// ReplyToCleared returns if the "reply_to" field was cleared in this mutation.
func (m *NotificationMutation) ReplyToCleared() bool {
	_, ok := m.clearedFields[notification.FieldReplyTo]
	return ok
}

// ResetReplyTo resets all changes to the "reply_to" field.
func (m *NotificationMutation) ResetReplyTo() {
	m.reply_to = nil
	delete(m.clearedFields, notification.FieldReplyTo)
}

// SetTag sets the "tag" field.
func (m *NotificationMutation) SetTag(s string) {
	m.tag = &s
}

// Tag returns the value of the "tag" field in the mutation.
func (m *NotificationMutation) Tag() (r string, exists bool) {
	v := m.tag
	if v == nil {
		return
	}
	return *v, true
}

// OldTag returns the old "tag" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldTag(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTag is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTag requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTag: %w", err)
	}
	return oldValue.Tag, nil
}

// ClearTag clears the value of the "tag" field.
func (m *NotificationMutation) ClearTag() {
	m.tag = nil
	m.clearedFields[notification.FieldTag] = struct{}{}
}

// TagCleared returns if the "tag" field was cleared in this mutation.
func (m *NotificationMutation) TagCleared() bool {
	_, ok := m.clearedFields[notification.FieldTag]
	return ok
}

// ResetTag resets all changes to the "tag" field.
func (m *NotificationMutation) ResetTag() {
	m.tag = nil
	delete(m.clearedFields, notification.FieldTag)
}

// SetAddress sets the "address" field.
func (m *NotificationMutation) SetAddress(t types.Address) {
	m.address = &t
}

// Address returns the value of the "address" field in the mutation.
func (m *NotificationMutation) Address() (r types.Address, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldAddress(ctx context.Context) (v types.Address, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *NotificationMutation) ResetAddress() {
	m.address = nil
}

// SetRequestID sets the "request_id" field.
func (m *NotificationMutation) SetRequestID(s string) {
	m.request_id = &s
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *NotificationMutation) RequestID() (r string, exists bool) {
	v := m.request_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldRequestID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *NotificationMutation) ResetRequestID() {
	m.request_id = nil
}

// SetScheduleTs sets the "schedule_ts" field.
func (m *NotificationMutation) SetScheduleTs(i int64) {
	m.schedule_ts = &i
	m.addschedule_ts = nil
}

// ScheduleTs returns the value of the "schedule_ts" field in the mutation.
func (m *NotificationMutation) ScheduleTs() (r int64, exists bool) {
	v := m.schedule_ts
	if v == nil {
		return
	}
	return *v, true
}

// OldScheduleTs returns the old "schedule_ts" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldScheduleTs(ctx context.Context) (v *int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScheduleTs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScheduleTs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScheduleTs: %w", err)
	}
	return oldValue.ScheduleTs, nil
}

// AddScheduleTs adds i to the "schedule_ts" field.
func (m *NotificationMutation) AddScheduleTs(i int64) {
	if m.addschedule_ts != nil {
		*m.addschedule_ts += i
	} else {
		m.addschedule_ts = &i
	}
}

// AddedScheduleTs returns the value that was added to the "schedule_ts" field in this mutation.
func (m *NotificationMutation) AddedScheduleTs() (r int64, exists bool) {
	v := m.addschedule_ts
	if v == nil {
		return
	}
	return *v, true
}

// ClearScheduleTs clears the value of the "schedule_ts" field.
func (m *NotificationMutation) ClearScheduleTs() {
	m.schedule_ts = nil
	m.addschedule_ts = nil
	m.clearedFields[notification.FieldScheduleTs] = struct{}{}
}

// ScheduleTsCleared returns if the "schedule_ts" field was cleared in this mutation.
func (m *NotificationMutation) ScheduleTsCleared() bool {
	_, ok := m.clearedFields[notification.FieldScheduleTs]
	return ok
}

// ResetScheduleTs resets all changes to the "schedule_ts" field.
func (m *NotificationMutation) ResetScheduleTs() {
	m.schedule_ts = nil
	m.addschedule_ts = nil
	delete(m.clearedFields, notification.FieldScheduleTs)
}

// SetType sets the "type" field.
func (m *NotificationMutation) SetType(n notification.Type) {
	m._type = &n
}

// GetType returns the value of the "type" field in the mutation.
func (m *NotificationMutation) GetType() (r notification.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldType(ctx context.Context) (v notification.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *NotificationMutation) ResetType() {
	m._type = nil
}

// SetStatus sets the "status" field.
func (m *NotificationMutation) SetStatus(n notification.Status) {
	m.status = &n
}

// Status returns the value of the "status" field in the mutation.
func (m *NotificationMutation) Status() (r notification.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldStatus(ctx context.Context) (v notification.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *NotificationMutation) ResetStatus() {
	m.status = nil
}

// SetMeta sets the "meta" field.
func (m *NotificationMutation) SetMeta(sm *schema.NotificationMeta) {
	m.meta = &sm
}

// Meta returns the value of the "meta" field in the mutation.
func (m *NotificationMutation) Meta() (r *schema.NotificationMeta, exists bool) {
	v := m.meta
	if v == nil {
		return
	}
	return *v, true
}

// OldMeta returns the old "meta" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldMeta(ctx context.Context) (v *schema.NotificationMeta, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMeta is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMeta requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMeta: %w", err)
	}
	return oldValue.Meta, nil
}

// ClearMeta clears the value of the "meta" field.
func (m *NotificationMutation) ClearMeta() {
	m.meta = nil
	m.clearedFields[notification.FieldMeta] = struct{}{}
}

// MetaCleared returns if the "meta" field was cleared in this mutation.
func (m *NotificationMutation) MetaCleared() bool {
	_, ok := m.clearedFields[notification.FieldMeta]
	return ok
}

// ResetMeta resets all changes to the "meta" field.
func (m *NotificationMutation) ResetMeta() {
	m.meta = nil
	delete(m.clearedFields, notification.FieldMeta)
}

// SetErrorMessage sets the "error_message" field.
func (m *NotificationMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *NotificationMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldErrorMessage(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *NotificationMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[notification.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *NotificationMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[notification.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *NotificationMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, notification.FieldErrorMessage)
}

// Where appends a list predicates to the NotificationMutation builder.
func (m *NotificationMutation) Where(ps ...predicate.Notification) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotificationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotificationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Notification, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotificationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotificationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Notification).
func (m *NotificationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotificationMutation) Fields() []string {
	fields := make([]string, 0, 15)
	if m.create_time != nil {
		fields = append(fields, notification.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, notification.FieldUpdateTime)
	}
	if m.body != nil {
		fields = append(fields, notification.FieldBody)
	}
	if m.headline != nil {
		fields = append(fields, notification.FieldHeadline)
	}
	if m.name != nil {
		fields = append(fields, notification.FieldName)
	}
	if m.from != nil {
		fields = append(fields, notification.FieldFrom)
	}
	if m.reply_to != nil {
		fields = append(fields, notification.FieldReplyTo)
	}
	if m.tag != nil {
		fields = append(fields, notification.FieldTag)
	}
	if m.address != nil {
		fields = append(fields, notification.FieldAddress)
	}
	if m.request_id != nil {
		fields = append(fields, notification.FieldRequestID)
	}
	if m.schedule_ts != nil {
		fields = append(fields, notification.FieldScheduleTs)
	}
	if m._type != nil {
		fields = append(fields, notification.FieldType)
	}
	if m.status != nil {
		fields = append(fields, notification.FieldStatus)
	}
	if m.meta != nil {
		fields = append(fields, notification.FieldMeta)
	}
	if m.error_message != nil {
		fields = append(fields, notification.FieldErrorMessage)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotificationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notification.FieldCreateTime:
		return m.CreateTime()
	case notification.FieldUpdateTime:
		return m.UpdateTime()
	case notification.FieldBody:
		return m.Body()
	case notification.FieldHeadline:
		return m.Headline()
	case notification.FieldName:
		return m.Name()
	case notification.FieldFrom:
		return m.From()
	case notification.FieldReplyTo:
		return m.ReplyTo()
	case notification.FieldTag:
		return m.Tag()
	case notification.FieldAddress:
		return m.Address()
	case notification.FieldRequestID:
		return m.RequestID()
	case notification.FieldScheduleTs:
		return m.ScheduleTs()
	case notification.FieldType:
		return m.GetType()
	case notification.FieldStatus:
		return m.Status()
	case notification.FieldMeta:
		return m.Meta()
	case notification.FieldErrorMessage:
		return m.ErrorMessage()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotificationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notification.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case notification.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case notification.FieldBody:
		return m.OldBody(ctx)
	case notification.FieldHeadline:
		return m.OldHeadline(ctx)
	case notification.FieldName:
		return m.OldName(ctx)
	case notification.FieldFrom:
		return m.OldFrom(ctx)
	case notification.FieldReplyTo:
		return m.OldReplyTo(ctx)
	case notification.FieldTag:
		return m.OldTag(ctx)
	case notification.FieldAddress:
		return m.OldAddress(ctx)
	case notification.FieldRequestID:
		return m.OldRequestID(ctx)
	case notification.FieldScheduleTs:
		return m.OldScheduleTs(ctx)
	case notification.FieldType:
		return m.OldType(ctx)
	case notification.FieldStatus:
		return m.OldStatus(ctx)
	case notification.FieldMeta:
		return m.OldMeta(ctx)
	case notification.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	}
	return nil, fmt.Errorf("unknown Notification field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotificationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notification.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case notification.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case notification.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case notification.FieldHeadline:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeadline(v)
		return nil
	case notification.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case notification.FieldFrom:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFrom(v)
		return nil
	case notification.FieldReplyTo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReplyTo(v)
		return nil
	case notification.FieldTag:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTag(v)
		return nil
	case notification.FieldAddress:
		v, ok := value.(types.Address)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case notification.FieldRequestID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case notification.FieldScheduleTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScheduleTs(v)
		return nil
	case notification.FieldType:
		v, ok := value.(notification.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case notification.FieldStatus:
		v, ok := value.(notification.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case notification.FieldMeta:
		v, ok := value.(*schema.NotificationMeta)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMeta(v)
		return nil
	case notification.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	}
	return fmt.Errorf("unknown Notification field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotificationMutation) AddedFields() []string {
	var fields []string
	if m.addschedule_ts != nil {
		fields = append(fields, notification.FieldScheduleTs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotificationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case notification.FieldScheduleTs:
		return m.AddedScheduleTs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotificationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case notification.FieldScheduleTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddScheduleTs(v)
		return nil
	}
	return fmt.Errorf("unknown Notification numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotificationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(notification.FieldHeadline) {
		fields = append(fields, notification.FieldHeadline)
	}
	if m.FieldCleared(notification.FieldName) {
		fields = append(fields, notification.FieldName)
	}
	if m.FieldCleared(notification.FieldFrom) {
		fields = append(fields, notification.FieldFrom)
	}
	if m.FieldCleared(notification.FieldReplyTo) {
		fields = append(fields, notification.FieldReplyTo)
	}
	if m.FieldCleared(notification.FieldTag) {
		fields = append(fields, notification.FieldTag)
	}
	if m.FieldCleared(notification.FieldScheduleTs) {
		fields = append(fields, notification.FieldScheduleTs)
	}
	if m.FieldCleared(notification.FieldMeta) {
		fields = append(fields, notification.FieldMeta)
	}
	if m.FieldCleared(notification.FieldErrorMessage) {
		fields = append(fields, notification.FieldErrorMessage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotificationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotificationMutation) ClearField(name string) error {
	switch name {
	case notification.FieldHeadline:
		m.ClearHeadline()
		return nil
	case notification.FieldName:
		m.ClearName()
		return nil
	case notification.FieldFrom:
		m.ClearFrom()
		return nil
	case notification.FieldReplyTo:
		m.ClearReplyTo()
		return nil
	case notification.FieldTag:
		m.ClearTag()
		return nil
	case notification.FieldScheduleTs:
		m.ClearScheduleTs()
		return nil
	case notification.FieldMeta:
		m.ClearMeta()
		return nil
	case notification.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	}
	return fmt.Errorf("unknown Notification nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotificationMutation) ResetField(name string) error {
	switch name {
	case notification.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case notification.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case notification.FieldBody:
		m.ResetBody()
		return nil
	case notification.FieldHeadline:
		m.ResetHeadline()
		return nil
	case notification.FieldName:
		m.ResetName()
		return nil
	case notification.FieldFrom:
		m.ResetFrom()
		return nil
	case notification.FieldReplyTo:
		m.ResetReplyTo()
		return nil
	case notification.FieldTag:
		m.ResetTag()
		return nil
	case notification.FieldAddress:
		m.ResetAddress()
		return nil
	case notification.FieldRequestID:
		m.ResetRequestID()
		return nil
	case notification.FieldScheduleTs:
		m.ResetScheduleTs()
		return nil
	case notification.FieldType:
		m.ResetType()
		return nil
	case notification.FieldStatus:
		m.ResetStatus()
		return nil
	case notification.FieldMeta:
		m.ResetMeta()
		return nil
	case notification.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	}
	return fmt.Errorf("unknown Notification field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotificationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotificationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotificationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotificationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotificationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotificationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotificationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Notification unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotificationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Notification edge %s", name)
}
