// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/notification"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/schema"
	"gitlab.com/healthcare-integration/golang/notification-service/types"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (nc *NotificationCreate) SetCreateTime(t time.Time) *NotificationCreate {
	nc.mutation.SetCreateTime(t)
	return nc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableCreateTime(t *time.Time) *NotificationCreate {
	if t != nil {
		nc.SetCreateTime(*t)
	}
	return nc
}

// SetUpdateTime sets the "update_time" field.
func (nc *NotificationCreate) SetUpdateTime(t time.Time) *NotificationCreate {
	nc.mutation.SetUpdateTime(t)
	return nc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableUpdateTime(t *time.Time) *NotificationCreate {
	if t != nil {
		nc.SetUpdateTime(*t)
	}
	return nc
}

// SetBody sets the "body" field.
func (nc *NotificationCreate) SetBody(s string) *NotificationCreate {
	nc.mutation.SetBody(s)
	return nc
}

// SetHeadline sets the "headline" field.
func (nc *NotificationCreate) SetHeadline(s string) *NotificationCreate {
	nc.mutation.SetHeadline(s)
	return nc
}

// SetNillableHeadline sets the "headline" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableHeadline(s *string) *NotificationCreate {
	if s != nil {
		nc.SetHeadline(*s)
	}
	return nc
}

// SetName sets the "name" field.
func (nc *NotificationCreate) SetName(s string) *NotificationCreate {
	nc.mutation.SetName(s)
	return nc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableName(s *string) *NotificationCreate {
	if s != nil {
		nc.SetName(*s)
	}
	return nc
}

// SetFrom sets the "from" field.
func (nc *NotificationCreate) SetFrom(s string) *NotificationCreate {
	nc.mutation.SetFrom(s)
	return nc
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableFrom(s *string) *NotificationCreate {
	if s != nil {
		nc.SetFrom(*s)
	}
	return nc
}

// SetReplyTo sets the "reply_to" field.
func (nc *NotificationCreate) SetReplyTo(s string) *NotificationCreate {
	nc.mutation.SetReplyTo(s)
	return nc
}

// SetNillableReplyTo sets the "reply_to" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableReplyTo(s *string) *NotificationCreate {
	if s != nil {
		nc.SetReplyTo(*s)
	}
	return nc
}

// SetTag sets the "tag" field.
func (nc *NotificationCreate) SetTag(s string) *NotificationCreate {
	nc.mutation.SetTag(s)
	return nc
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableTag(s *string) *NotificationCreate {
	if s != nil {
		nc.SetTag(*s)
	}
	return nc
}

// SetAddress sets the "address" field.
func (nc *NotificationCreate) SetAddress(t types.Address) *NotificationCreate {
	nc.mutation.SetAddress(t)
	return nc
}

// SetRequestID sets the "request_id" field.
func (nc *NotificationCreate) SetRequestID(s string) *NotificationCreate {
	nc.mutation.SetRequestID(s)
	return nc
}

// SetScheduleTs sets the "schedule_ts" field.
func (nc *NotificationCreate) SetScheduleTs(i int64) *NotificationCreate {
	nc.mutation.SetScheduleTs(i)
	return nc
}

// SetNillableScheduleTs sets the "schedule_ts" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableScheduleTs(i *int64) *NotificationCreate {
	if i != nil {
		nc.SetScheduleTs(*i)
	}
	return nc
}

// SetType sets the "type" field.
func (nc *NotificationCreate) SetType(n notification.Type) *NotificationCreate {
	nc.mutation.SetType(n)
	return nc
}

// SetStatus sets the "status" field.
func (nc *NotificationCreate) SetStatus(n notification.Status) *NotificationCreate {
	nc.mutation.SetStatus(n)
	return nc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableStatus(n *notification.Status) *NotificationCreate {
	if n != nil {
		nc.SetStatus(*n)
	}
	return nc
}

// SetMeta sets the "meta" field.
func (nc *NotificationCreate) SetMeta(sm *schema.NotificationMeta) *NotificationCreate {
	nc.mutation.SetMeta(sm)
	return nc
}

// SetErrorMessage sets the "error_message" field.
func (nc *NotificationCreate) SetErrorMessage(s string) *NotificationCreate {
	nc.mutation.SetErrorMessage(s)
	return nc
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableErrorMessage(s *string) *NotificationCreate {
	if s != nil {
		nc.SetErrorMessage(*s)
	}
	return nc
}

// Mutation returns the NotificationMutation object of the builder.
func (nc *NotificationCreate) Mutation() *NotificationMutation {
	return nc.mutation
}

// Save creates the Notification in the database.
func (nc *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NotificationCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NotificationCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NotificationCreate) defaults() {
	if _, ok := nc.mutation.CreateTime(); !ok {
		v := notification.DefaultCreateTime()
		nc.mutation.SetCreateTime(v)
	}
	if _, ok := nc.mutation.UpdateTime(); !ok {
		v := notification.DefaultUpdateTime()
		nc.mutation.SetUpdateTime(v)
	}
	if _, ok := nc.mutation.Status(); !ok {
		v := notification.DefaultStatus
		nc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NotificationCreate) check() error {
	if _, ok := nc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Notification.create_time"`)}
	}
	if _, ok := nc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Notification.update_time"`)}
	}
	if _, ok := nc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Notification.body"`)}
	}
	if _, ok := nc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Notification.address"`)}
	}
	if _, ok := nc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "Notification.request_id"`)}
	}
	if _, ok := nc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Notification.type"`)}
	}
	if v, ok := nc.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if _, ok := nc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Notification.status"`)}
	}
	if v, ok := nc.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (nc *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	)
	if value, ok := nc.mutation.CreateTime(); ok {
		_spec.SetField(notification.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := nc.mutation.UpdateTime(); ok {
		_spec.SetField(notification.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := nc.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := nc.mutation.Headline(); ok {
		_spec.SetField(notification.FieldHeadline, field.TypeString, value)
		_node.Headline = value
	}
	if value, ok := nc.mutation.Name(); ok {
		_spec.SetField(notification.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := nc.mutation.From(); ok {
		_spec.SetField(notification.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := nc.mutation.ReplyTo(); ok {
		_spec.SetField(notification.FieldReplyTo, field.TypeString, value)
		_node.ReplyTo = value
	}
	if value, ok := nc.mutation.Tag(); ok {
		_spec.SetField(notification.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if value, ok := nc.mutation.Address(); ok {
		_spec.SetField(notification.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := nc.mutation.RequestID(); ok {
		_spec.SetField(notification.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := nc.mutation.ScheduleTs(); ok {
		_spec.SetField(notification.FieldScheduleTs, field.TypeInt64, value)
		_node.ScheduleTs = &value
	}
	if value, ok := nc.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := nc.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := nc.mutation.Meta(); ok {
		_spec.SetField(notification.FieldMeta, field.TypeJSON, value)
		_node.Meta = value
	}
	if value, ok := nc.mutation.ErrorMessage(); ok {
		_spec.SetField(notification.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (ncb *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notification, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
