// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/notification"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/predicate"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/schema"
	"gitlab.com/healthcare-integration/golang/notification-service/types"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nu *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetUpdateTime sets the "update_time" field.
func (nu *NotificationUpdate) SetUpdateTime(t time.Time) *NotificationUpdate {
	nu.mutation.SetUpdateTime(t)
	return nu
}

// SetBody sets the "body" field.
func (nu *NotificationUpdate) SetBody(s string) *NotificationUpdate {
	nu.mutation.SetBody(s)
	return nu
}

// SetHeadline sets the "headline" field.
func (nu *NotificationUpdate) SetHeadline(s string) *NotificationUpdate {
	nu.mutation.SetHeadline(s)
	return nu
}

// SetNillableHeadline sets the "headline" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableHeadline(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetHeadline(*s)
	}
	return nu
}

// ClearHeadline clears the value of the "headline" field.
func (nu *NotificationUpdate) ClearHeadline() *NotificationUpdate {
	nu.mutation.ClearHeadline()
	return nu
}

// SetName sets the "name" field.
func (nu *NotificationUpdate) SetName(s string) *NotificationUpdate {
	nu.mutation.SetName(s)
	return nu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableName(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetName(*s)
	}
	return nu
}

// ClearName clears the value of the "name" field.
func (nu *NotificationUpdate) ClearName() *NotificationUpdate {
	nu.mutation.ClearName()
	return nu
}

// SetAddress sets the "address" field.
func (nu *NotificationUpdate) SetAddress(t types.Address) *NotificationUpdate {
	nu.mutation.SetAddress(t)
	return nu
}

// SetRequestID sets the "request_id" field.
func (nu *NotificationUpdate) SetRequestID(s string) *NotificationUpdate {
	nu.mutation.SetRequestID(s)
	return nu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableRequestID(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetRequestID(*s)
	}
	return nu
}

// ClearRequestID clears the value of the "request_id" field.
func (nu *NotificationUpdate) ClearRequestID() *NotificationUpdate {
	nu.mutation.ClearRequestID()
	return nu
}

// SetScheduleTs sets the "schedule_ts" field.
func (nu *NotificationUpdate) SetScheduleTs(i int64) *NotificationUpdate {
	nu.mutation.ResetScheduleTs()
	nu.mutation.SetScheduleTs(i)
	return nu
}

// SetNillableScheduleTs sets the "schedule_ts" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableScheduleTs(i *int64) *NotificationUpdate {
	if i != nil {
		nu.SetScheduleTs(*i)
	}
	return nu
}

// AddScheduleTs adds i to the "schedule_ts" field.
func (nu *NotificationUpdate) AddScheduleTs(i int64) *NotificationUpdate {
	nu.mutation.AddScheduleTs(i)
	return nu
}

// ClearScheduleTs clears the value of the "schedule_ts" field.
func (nu *NotificationUpdate) ClearScheduleTs() *NotificationUpdate {
	nu.mutation.ClearScheduleTs()
	return nu
}

// SetType sets the "type" field.
func (nu *NotificationUpdate) SetType(n notification.Type) *NotificationUpdate {
	nu.mutation.SetType(n)
	return nu
}

// SetStatus sets the "status" field.
func (nu *NotificationUpdate) SetStatus(n notification.Status) *NotificationUpdate {
	nu.mutation.SetStatus(n)
	return nu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableStatus(n *notification.Status) *NotificationUpdate {
	if n != nil {
		nu.SetStatus(*n)
	}
	return nu
}

// SetMeta sets the "meta" field.
func (nu *NotificationUpdate) SetMeta(sm *schema.NotificationMeta) *NotificationUpdate {
	nu.mutation.SetMeta(sm)
	return nu
}

// ClearMeta clears the value of the "meta" field.
func (nu *NotificationUpdate) ClearMeta() *NotificationUpdate {
	nu.mutation.ClearMeta()
	return nu
}

// SetErrorMessage sets the "error_message" field.
func (nu *NotificationUpdate) SetErrorMessage(s string) *NotificationUpdate {
	nu.mutation.SetErrorMessage(s)
	return nu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableErrorMessage(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetErrorMessage(*s)
	}
	return nu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (nu *NotificationUpdate) ClearErrorMessage() *NotificationUpdate {
	nu.mutation.ClearErrorMessage()
	return nu
}

// Mutation returns the NotificationMutation object of the builder.
func (nu *NotificationUpdate) Mutation() *NotificationMutation {
	return nu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotificationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	nu.defaults()
	if len(nu.hooks) == 0 {
		if err = nu.check(); err != nil {
			return 0, err
		}
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotificationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nu.check(); err != nil {
				return 0, err
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			if nu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotificationUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NotificationUpdate) defaults() {
	if _, ok := nu.mutation.UpdateTime(); !ok {
		v := notification.UpdateDefaultUpdateTime()
		nu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotificationUpdate) check() error {
	if v, ok := nu.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := nu.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (nu *NotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notification.Table,
			Columns: notification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notification.FieldID,
			},
		},
	}
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notification.FieldUpdateTime,
		})
	}
	if value, ok := nu.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldBody,
		})
	}
	if value, ok := nu.mutation.Headline(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldHeadline,
		})
	}
	if nu.mutation.HeadlineCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldHeadline,
		})
	}
	if value, ok := nu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldName,
		})
	}
	if nu.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldName,
		})
	}
	if value, ok := nu.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldAddress,
		})
	}
	if value, ok := nu.mutation.RequestID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldRequestID,
		})
	}
	if nu.mutation.RequestIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldRequestID,
		})
	}
	if value, ok := nu.mutation.ScheduleTs(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: notification.FieldScheduleTs,
		})
	}
	if value, ok := nu.mutation.AddedScheduleTs(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: notification.FieldScheduleTs,
		})
	}
	if nu.mutation.ScheduleTsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: notification.FieldScheduleTs,
		})
	}
	if value, ok := nu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: notification.FieldType,
		})
	}
	if value, ok := nu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: notification.FieldStatus,
		})
	}
	if value, ok := nu.mutation.Meta(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: notification.FieldMeta,
		})
	}
	if nu.mutation.MetaCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: notification.FieldMeta,
		})
	}
	if value, ok := nu.mutation.ErrorMessage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldErrorMessage,
		})
	}
	if nu.mutation.ErrorMessageCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldErrorMessage,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetUpdateTime sets the "update_time" field.
func (nuo *NotificationUpdateOne) SetUpdateTime(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetUpdateTime(t)
	return nuo
}

// SetBody sets the "body" field.
func (nuo *NotificationUpdateOne) SetBody(s string) *NotificationUpdateOne {
	nuo.mutation.SetBody(s)
	return nuo
}

// SetHeadline sets the "headline" field.
func (nuo *NotificationUpdateOne) SetHeadline(s string) *NotificationUpdateOne {
	nuo.mutation.SetHeadline(s)
	return nuo
}

// SetNillableHeadline sets the "headline" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableHeadline(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetHeadline(*s)
	}
	return nuo
}

// ClearHeadline clears the value of the "headline" field.
func (nuo *NotificationUpdateOne) ClearHeadline() *NotificationUpdateOne {
	nuo.mutation.ClearHeadline()
	return nuo
}

// SetName sets the "name" field.
func (nuo *NotificationUpdateOne) SetName(s string) *NotificationUpdateOne {
	nuo.mutation.SetName(s)
	return nuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableName(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetName(*s)
	}
	return nuo
}

// ClearName clears the value of the "name" field.
func (nuo *NotificationUpdateOne) ClearName() *NotificationUpdateOne {
	nuo.mutation.ClearName()
	return nuo
}

// SetAddress sets the "address" field.
func (nuo *NotificationUpdateOne) SetAddress(t types.Address) *NotificationUpdateOne {
	nuo.mutation.SetAddress(t)
	return nuo
}

// SetRequestID sets the "request_id" field.
func (nuo *NotificationUpdateOne) SetRequestID(s string) *NotificationUpdateOne {
	nuo.mutation.SetRequestID(s)
	return nuo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableRequestID(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetRequestID(*s)
	}
	return nuo
}

// ClearRequestID clears the value of the "request_id" field.
func (nuo *NotificationUpdateOne) ClearRequestID() *NotificationUpdateOne {
	nuo.mutation.ClearRequestID()
	return nuo
}

// SetScheduleTs sets the "schedule_ts" field.
func (nuo *NotificationUpdateOne) SetScheduleTs(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetScheduleTs()
	nuo.mutation.SetScheduleTs(i)
	return nuo
}

// SetNillableScheduleTs sets the "schedule_ts" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableScheduleTs(i *int64) *NotificationUpdateOne {
	if i != nil {
		nuo.SetScheduleTs(*i)
	}
	return nuo
}

// AddScheduleTs adds i to the "schedule_ts" field.
func (nuo *NotificationUpdateOne) AddScheduleTs(i int64) *NotificationUpdateOne {
	nuo.mutation.AddScheduleTs(i)
	return nuo
}

// ClearScheduleTs clears the value of the "schedule_ts" field.
func (nuo *NotificationUpdateOne) ClearScheduleTs() *NotificationUpdateOne {
	nuo.mutation.ClearScheduleTs()
	return nuo
}

// SetType sets the "type" field.
func (nuo *NotificationUpdateOne) SetType(n notification.Type) *NotificationUpdateOne {
	nuo.mutation.SetType(n)
	return nuo
}

// SetStatus sets the "status" field.
func (nuo *NotificationUpdateOne) SetStatus(n notification.Status) *NotificationUpdateOne {
	nuo.mutation.SetStatus(n)
	return nuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableStatus(n *notification.Status) *NotificationUpdateOne {
	if n != nil {
		nuo.SetStatus(*n)
	}
	return nuo
}

// SetMeta sets the "meta" field.
func (nuo *NotificationUpdateOne) SetMeta(sm *schema.NotificationMeta) *NotificationUpdateOne {
	nuo.mutation.SetMeta(sm)
	return nuo
}

// ClearMeta clears the value of the "meta" field.
func (nuo *NotificationUpdateOne) ClearMeta() *NotificationUpdateOne {
	nuo.mutation.ClearMeta()
	return nuo
}

// SetErrorMessage sets the "error_message" field.
func (nuo *NotificationUpdateOne) SetErrorMessage(s string) *NotificationUpdateOne {
	nuo.mutation.SetErrorMessage(s)
	return nuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableErrorMessage(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetErrorMessage(*s)
	}
	return nuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (nuo *NotificationUpdateOne) ClearErrorMessage() *NotificationUpdateOne {
	nuo.mutation.ClearErrorMessage()
	return nuo
}

// Mutation returns the NotificationMutation object of the builder.
func (nuo *NotificationUpdateOne) Mutation() *NotificationMutation {
	return nuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notification entity.
func (nuo *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	var (
		err  error
		node *Notification
	)
	nuo.defaults()
	if len(nuo.hooks) == 0 {
		if err = nuo.check(); err != nil {
			return nil, err
		}
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotificationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nuo.check(); err != nil {
				return nil, err
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			if nuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NotificationUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdateTime(); !ok {
		v := notification.UpdateDefaultUpdateTime()
		nuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotificationUpdateOne) check() error {
	if v, ok := nuo.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := nuo.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (nuo *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notification.Table,
			Columns: notification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notification.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notification.FieldUpdateTime,
		})
	}
	if value, ok := nuo.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldBody,
		})
	}
	if value, ok := nuo.mutation.Headline(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldHeadline,
		})
	}
	if nuo.mutation.HeadlineCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldHeadline,
		})
	}
	if value, ok := nuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldName,
		})
	}
	if nuo.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldName,
		})
	}
	if value, ok := nuo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldAddress,
		})
	}
	if value, ok := nuo.mutation.RequestID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldRequestID,
		})
	}
	if nuo.mutation.RequestIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldRequestID,
		})
	}
	if value, ok := nuo.mutation.ScheduleTs(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: notification.FieldScheduleTs,
		})
	}
	if value, ok := nuo.mutation.AddedScheduleTs(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: notification.FieldScheduleTs,
		})
	}
	if nuo.mutation.ScheduleTsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: notification.FieldScheduleTs,
		})
	}
	if value, ok := nuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: notification.FieldType,
		})
	}
	if value, ok := nuo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: notification.FieldStatus,
		})
	}
	if value, ok := nuo.mutation.Meta(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: notification.FieldMeta,
		})
	}
	if nuo.mutation.MetaCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: notification.FieldMeta,
		})
	}
	if value, ok := nuo.mutation.ErrorMessage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notification.FieldErrorMessage,
		})
	}
	if nuo.mutation.ErrorMessageCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notification.FieldErrorMessage,
		})
	}
	_node = &Notification{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
