// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.smartbet.am/golang/notification/ent/partnerconfig"
	"gitlab.smartbet.am/golang/notification/ent/schema"
)

// PartnerConfig is the model entity for the PartnerConfig schema.
type PartnerConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// EmailProviders holds the value of the "email_providers" field.
	EmailProviders []schema.ProviderConfig `json:"email_providers,omitempty"`
	// SmsProviders holds the value of the "sms_providers" field.
	SmsProviders []schema.ProviderConfig `json:"sms_providers,omitempty"`
	// PushProviders holds the value of the "push_providers" field.
	PushProviders []schema.ProviderConfig `json:"push_providers,omitempty"`
	// BatchConfig holds the value of the "batch_config" field.
	BatchConfig *schema.BatchConfig `json:"batch_config,omitempty"`
	// RateLimits holds the value of the "rate_limits" field.
	RateLimits map[string]schema.RateLimit `json:"rate_limits,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PartnerConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case partnerconfig.FieldEmailProviders, partnerconfig.FieldSmsProviders, partnerconfig.FieldPushProviders, partnerconfig.FieldBatchConfig, partnerconfig.FieldRateLimits:
			values[i] = new([]byte)
		case partnerconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case partnerconfig.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case partnerconfig.FieldID:
			values[i] = new(sql.NullString)
		case partnerconfig.FieldCreateTime, partnerconfig.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PartnerConfig fields.
func (pc *PartnerConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case partnerconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pc.ID = value.String
			}
		case partnerconfig.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				pc.CreateTime = value.Time
			}
		case partnerconfig.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				pc.UpdateTime = value.Time
			}
		case partnerconfig.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				pc.TenantID = value.Int64
			}
		case partnerconfig.FieldEmailProviders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field email_providers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pc.EmailProviders); err != nil {
					return fmt.Errorf("unmarshal field email_providers: %w", err)
				}
			}
		case partnerconfig.FieldSmsProviders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sms_providers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pc.SmsProviders); err != nil {
					return fmt.Errorf("unmarshal field sms_providers: %w", err)
				}
			}
		case partnerconfig.FieldPushProviders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field push_providers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pc.PushProviders); err != nil {
					return fmt.Errorf("unmarshal field push_providers: %w", err)
				}
			}
		case partnerconfig.FieldBatchConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field batch_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pc.BatchConfig); err != nil {
					return fmt.Errorf("unmarshal field batch_config: %w", err)
				}
			}
		case partnerconfig.FieldRateLimits:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limits", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pc.RateLimits); err != nil {
					return fmt.Errorf("unmarshal field rate_limits: %w", err)
				}
			}
		case partnerconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				pc.Enabled = value.Bool
			}
		default:
			pc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PartnerConfig.
// This includes values selected through modifiers, order, etc.
func (pc *PartnerConfig) Value(name string) (ent.Value, error) {
	return pc.selectValues.Get(name)
}

// Update returns a builder for updating this PartnerConfig.
// Note that you need to call PartnerConfig.Unwrap() before calling this method if this PartnerConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (pc *PartnerConfig) Update() *PartnerConfigUpdateOne {
	return NewPartnerConfigClient(pc.config).UpdateOne(pc)
}

// Unwrap unwraps the PartnerConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pc *PartnerConfig) Unwrap() *PartnerConfig {
	_tx, ok := pc.config.driver.(*txDriver)
	if !ok {
		panic("ent: PartnerConfig is not a transactional entity")
	}
	pc.config.driver = _tx.drv
	return pc
}

// String implements the fmt.Stringer.
func (pc *PartnerConfig) String() string {
	var builder strings.Builder
	builder.WriteString("PartnerConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pc.ID))
	builder.WriteString("create_time=")
	builder.WriteString(pc.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(pc.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", pc.TenantID))
	builder.WriteString(", ")
	builder.WriteString("email_providers=")
	builder.WriteString(fmt.Sprintf("%v", pc.EmailProviders))
	builder.WriteString(", ")
	builder.WriteString("sms_providers=")
	builder.WriteString(fmt.Sprintf("%v", pc.SmsProviders))
	builder.WriteString(", ")
	builder.WriteString("push_providers=")
	builder.WriteString(fmt.Sprintf("%v", pc.PushProviders))
	builder.WriteString(", ")
	builder.WriteString("batch_config=")
	builder.WriteString(fmt.Sprintf("%v", pc.BatchConfig))
	builder.WriteString(", ")
	builder.WriteString("rate_limits=")
	builder.WriteString(fmt.Sprintf("%v", pc.RateLimits))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", pc.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// PartnerConfigs is a parsable slice of PartnerConfig.
type PartnerConfigs []*PartnerConfig
