// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.smartbet.am/golang/notification/ent/partnerconfig"
	"gitlab.smartbet.am/golang/notification/ent/schema"
)

// PartnerConfigCreate is the builder for creating a PartnerConfig entity.
type PartnerConfigCreate struct {
	config
	mutation *PartnerConfigMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (pcc *PartnerConfigCreate) SetCreateTime(t time.Time) *PartnerConfigCreate {
	pcc.mutation.SetCreateTime(t)
	return pcc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (pcc *PartnerConfigCreate) SetNillableCreateTime(t *time.Time) *PartnerConfigCreate {
	if t != nil {
		pcc.SetCreateTime(*t)
	}
	return pcc
}

// SetUpdateTime sets the "update_time" field.
func (pcc *PartnerConfigCreate) SetUpdateTime(t time.Time) *PartnerConfigCreate {
	pcc.mutation.SetUpdateTime(t)
	return pcc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (pcc *PartnerConfigCreate) SetNillableUpdateTime(t *time.Time) *PartnerConfigCreate {
	if t != nil {
		pcc.SetUpdateTime(*t)
	}
	return pcc
}

// SetTenantID sets the "tenant_id" field.
func (pcc *PartnerConfigCreate) SetTenantID(i int64) *PartnerConfigCreate {
	pcc.mutation.SetTenantID(i)
	return pcc
}

// SetEmailProviders sets the "email_providers" field.
func (pcc *PartnerConfigCreate) SetEmailProviders(sc []schema.ProviderConfig) *PartnerConfigCreate {
	pcc.mutation.SetEmailProviders(sc)
	return pcc
}

// SetSmsProviders sets the "sms_providers" field.
func (pcc *PartnerConfigCreate) SetSmsProviders(sc []schema.ProviderConfig) *PartnerConfigCreate {
	pcc.mutation.SetSmsProviders(sc)
	return pcc
}

// SetPushProviders sets the "push_providers" field.
func (pcc *PartnerConfigCreate) SetPushProviders(sc []schema.ProviderConfig) *PartnerConfigCreate {
	pcc.mutation.SetPushProviders(sc)
	return pcc
}

// SetBatchConfig sets the "batch_config" field.
func (pcc *PartnerConfigCreate) SetBatchConfig(sc *schema.BatchConfig) *PartnerConfigCreate {
	pcc.mutation.SetBatchConfig(sc)
	return pcc
}

// SetRateLimits sets the "rate_limits" field.
func (pcc *PartnerConfigCreate) SetRateLimits(ml map[string]schema.RateLimit) *PartnerConfigCreate {
	pcc.mutation.SetRateLimits(ml)
	return pcc
}

// SetEnabled sets the "enabled" field.
func (pcc *PartnerConfigCreate) SetEnabled(b bool) *PartnerConfigCreate {
	pcc.mutation.SetEnabled(b)
	return pcc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (pcc *PartnerConfigCreate) SetNillableEnabled(b *bool) *PartnerConfigCreate {
	if b != nil {
		pcc.SetEnabled(*b)
	}
	return pcc
}

// SetID sets the "id" field.
func (pcc *PartnerConfigCreate) SetID(s string) *PartnerConfigCreate {
	pcc.mutation.SetID(s)
	return pcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pcc *PartnerConfigCreate) SetNillableID(s *string) *PartnerConfigCreate {
	if s != nil {
		pcc.SetID(*s)
	}
	return pcc
}

// Mutation returns the PartnerConfigMutation object of the builder.
func (pcc *PartnerConfigCreate) Mutation() *PartnerConfigMutation {
	return pcc.mutation
}

// Save creates the PartnerConfig in the database.
func (pcc *PartnerConfigCreate) Save(ctx context.Context) (*PartnerConfig, error) {
	pcc.defaults()
	return withHooks(ctx, pcc.sqlSave, pcc.mutation, pcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *PartnerConfigCreate) SaveX(ctx context.Context) *PartnerConfig {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *PartnerConfigCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *PartnerConfigCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcc *PartnerConfigCreate) defaults() {
	if _, ok := pcc.mutation.CreateTime(); !ok {
		v := partnerconfig.DefaultCreateTime()
		pcc.mutation.SetCreateTime(v)
	}
	if _, ok := pcc.mutation.UpdateTime(); !ok {
		v := partnerconfig.DefaultUpdateTime()
		pcc.mutation.SetUpdateTime(v)
	}
	if _, ok := pcc.mutation.Enabled(); !ok {
		v := partnerconfig.DefaultEnabled
		pcc.mutation.SetEnabled(v)
	}
	if _, ok := pcc.mutation.ID(); !ok {
		v := partnerconfig.DefaultID
		pcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *PartnerConfigCreate) check() error {
	if _, ok := pcc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "PartnerConfig.create_time"`)}
	}
	if _, ok := pcc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "PartnerConfig.update_time"`)}
	}
	if _, ok := pcc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PartnerConfig.tenant_id"`)}
	}
	if _, ok := pcc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PartnerConfig.enabled"`)}
	}
	return nil
}

func (pcc *PartnerConfigCreate) sqlSave(ctx context.Context) (*PartnerConfig, error) {
	if err := pcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PartnerConfig.ID type: %T", _spec.ID.Value)
		}
	}
	pcc.mutation.id = &_node.ID
	pcc.mutation.done = true
	return _node, nil
}

func (pcc *PartnerConfigCreate) createSpec() (*PartnerConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &PartnerConfig{config: pcc.config}
		_spec = sqlgraph.NewCreateSpec(partnerconfig.Table, sqlgraph.NewFieldSpec(partnerconfig.FieldID, field.TypeString))
	)
	if id, ok := pcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pcc.mutation.CreateTime(); ok {
		_spec.SetField(partnerconfig.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := pcc.mutation.UpdateTime(); ok {
		_spec.SetField(partnerconfig.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := pcc.mutation.TenantID(); ok {
		_spec.SetField(partnerconfig.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := pcc.mutation.EmailProviders(); ok {
		_spec.SetField(partnerconfig.FieldEmailProviders, field.TypeJSON, value)
		_node.EmailProviders = value
	}
	if value, ok := pcc.mutation.SmsProviders(); ok {
		_spec.SetField(partnerconfig.FieldSmsProviders, field.TypeJSON, value)
		_node.SmsProviders = value
	}
	if value, ok := pcc.mutation.PushProviders(); ok {
		_spec.SetField(partnerconfig.FieldPushProviders, field.TypeJSON, value)
		_node.PushProviders = value
	}
	if value, ok := pcc.mutation.BatchConfig(); ok {
		_spec.SetField(partnerconfig.FieldBatchConfig, field.TypeJSON, value)
		_node.BatchConfig = value
	}
	if value, ok := pcc.mutation.RateLimits(); ok {
		_spec.SetField(partnerconfig.FieldRateLimits, field.TypeJSON, value)
		_node.RateLimits = value
	}
	if value, ok := pcc.mutation.Enabled(); ok {
		_spec.SetField(partnerconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// PartnerConfigCreateBulk is the builder for creating many PartnerConfig entities in bulk.
type PartnerConfigCreateBulk struct {
	config
	err      error
	builders []*PartnerConfigCreate
}

// Save creates the PartnerConfig entities in the database.
func (pccb *PartnerConfigCreateBulk) Save(ctx context.Context) ([]*PartnerConfig, error) {
	if pccb.err != nil {
		return nil, pccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*PartnerConfig, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PartnerConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *PartnerConfigCreateBulk) SaveX(ctx context.Context) []*PartnerConfig {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *PartnerConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *PartnerConfigCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
