// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"gitlab.smartbet.am/golang/notification/ent/partnerconfig"
	"gitlab.smartbet.am/golang/notification/ent/predicate"
	"gitlab.smartbet.am/golang/notification/ent/schema"
)

// PartnerConfigUpdate is the builder for updating PartnerConfig entities.
type PartnerConfigUpdate struct {
	config
	hooks    []Hook
	mutation *PartnerConfigMutation
}

// Where appends a list predicates to the PartnerConfigUpdate builder.
func (pcu *PartnerConfigUpdate) Where(ps ...predicate.PartnerConfig) *PartnerConfigUpdate {
	pcu.mutation.Where(ps...)
	return pcu
}

// SetUpdateTime sets the "update_time" field.
func (pcu *PartnerConfigUpdate) SetUpdateTime(t time.Time) *PartnerConfigUpdate {
	pcu.mutation.SetUpdateTime(t)
	return pcu
}

// SetTenantID sets the "tenant_id" field.
func (pcu *PartnerConfigUpdate) SetTenantID(i int64) *PartnerConfigUpdate {
	pcu.mutation.ResetTenantID()
	pcu.mutation.SetTenantID(i)
	return pcu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pcu *PartnerConfigUpdate) SetNillableTenantID(i *int64) *PartnerConfigUpdate {
	if i != nil {
		pcu.SetTenantID(*i)
	}
	return pcu
}

// AddTenantID adds i to the "tenant_id" field.
func (pcu *PartnerConfigUpdate) AddTenantID(i int64) *PartnerConfigUpdate {
	pcu.mutation.AddTenantID(i)
	return pcu
}

// SetEmailProviders sets the "email_providers" field.
func (pcu *PartnerConfigUpdate) SetEmailProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.SetEmailProviders(sc)
	return pcu
}

// AppendEmailProviders appends sc to the "email_providers" field.
func (pcu *PartnerConfigUpdate) AppendEmailProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.AppendEmailProviders(sc)
	return pcu
}

// ClearEmailProviders clears the value of the "email_providers" field.
func (pcu *PartnerConfigUpdate) ClearEmailProviders() *PartnerConfigUpdate {
	pcu.mutation.ClearEmailProviders()
	return pcu
}

// SetSmsProviders sets the "sms_providers" field.
func (pcu *PartnerConfigUpdate) SetSmsProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.SetSmsProviders(sc)
	return pcu
}

// AppendSmsProviders appends sc to the "sms_providers" field.
func (pcu *PartnerConfigUpdate) AppendSmsProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.AppendSmsProviders(sc)
	return pcu
}

// ClearSmsProviders clears the value of the "sms_providers" field.
func (pcu *PartnerConfigUpdate) ClearSmsProviders() *PartnerConfigUpdate {
	pcu.mutation.ClearSmsProviders()
	return pcu
}

// SetPushProviders sets the "push_providers" field.
func (pcu *PartnerConfigUpdate) SetPushProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.SetPushProviders(sc)
	return pcu
}

// AppendPushProviders appends sc to the "push_providers" field.
func (pcu *PartnerConfigUpdate) AppendPushProviders(sc []schema.ProviderConfig) *PartnerConfigUpdate {
	pcu.mutation.AppendPushProviders(sc)
	return pcu
}

// ClearPushProviders clears the value of the "push_providers" field.
func (pcu *PartnerConfigUpdate) ClearPushProviders() *PartnerConfigUpdate {
	pcu.mutation.ClearPushProviders()
	return pcu
}

// SetBatchConfig sets the "batch_config" field.
func (pcu *PartnerConfigUpdate) SetBatchConfig(sc *schema.BatchConfig) *PartnerConfigUpdate {
	pcu.mutation.SetBatchConfig(sc)
	return pcu
}

// ClearBatchConfig clears the value of the "batch_config" field.
func (pcu *PartnerConfigUpdate) ClearBatchConfig() *PartnerConfigUpdate {
	pcu.mutation.ClearBatchConfig()
	return pcu
}

// SetRateLimits sets the "rate_limits" field.
func (pcu *PartnerConfigUpdate) SetRateLimits(ml map[string]schema.RateLimit) *PartnerConfigUpdate {
	pcu.mutation.SetRateLimits(ml)
	return pcu
}

// ClearRateLimits clears the value of the "rate_limits" field.
func (pcu *PartnerConfigUpdate) ClearRateLimits() *PartnerConfigUpdate {
	pcu.mutation.ClearRateLimits()
	return pcu
}

// SetEnabled sets the "enabled" field.
func (pcu *PartnerConfigUpdate) SetEnabled(b bool) *PartnerConfigUpdate {
	pcu.mutation.SetEnabled(b)
	return pcu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (pcu *PartnerConfigUpdate) SetNillableEnabled(b *bool) *PartnerConfigUpdate {
	if b != nil {
		pcu.SetEnabled(*b)
	}
	return pcu
}

// Mutation returns the PartnerConfigMutation object of the builder.
func (pcu *PartnerConfigUpdate) Mutation() *PartnerConfigMutation {
	return pcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pcu *PartnerConfigUpdate) Save(ctx context.Context) (int, error) {
	pcu.defaults()
	return withHooks(ctx, pcu.sqlSave, pcu.mutation, pcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pcu *PartnerConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := pcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pcu *PartnerConfigUpdate) Exec(ctx context.Context) error {
	_, err := pcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcu *PartnerConfigUpdate) ExecX(ctx context.Context) {
	if err := pcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcu *PartnerConfigUpdate) defaults() {
	if _, ok := pcu.mutation.UpdateTime(); !ok {
		v := partnerconfig.UpdateDefaultUpdateTime()
		pcu.mutation.SetUpdateTime(v)
	}
}

func (pcu *PartnerConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(partnerconfig.Table, partnerconfig.Columns, sqlgraph.NewFieldSpec(partnerconfig.FieldID, field.TypeString))
	if ps := pcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcu.mutation.UpdateTime(); ok {
		_spec.SetField(partnerconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pcu.mutation.TenantID(); ok {
		_spec.SetField(partnerconfig.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := pcu.mutation.AddedTenantID(); ok {
		_spec.AddField(partnerconfig.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := pcu.mutation.EmailProviders(); ok {
		_spec.SetField(partnerconfig.FieldEmailProviders, field.TypeJSON, value)
	}
	if value, ok := pcu.mutation.AppendedEmailProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldEmailProviders, value)
		})
	}
	if pcu.mutation.EmailProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldEmailProviders, field.TypeJSON)
	}
	if value, ok := pcu.mutation.SmsProviders(); ok {
		_spec.SetField(partnerconfig.FieldSmsProviders, field.TypeJSON, value)
	}
	if value, ok := pcu.mutation.AppendedSmsProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldSmsProviders, value)
		})
	}
	if pcu.mutation.SmsProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldSmsProviders, field.TypeJSON)
	}
	if value, ok := pcu.mutation.PushProviders(); ok {
		_spec.SetField(partnerconfig.FieldPushProviders, field.TypeJSON, value)
	}
	if value, ok := pcu.mutation.AppendedPushProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldPushProviders, value)
		})
	}
	if pcu.mutation.PushProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldPushProviders, field.TypeJSON)
	}
	if value, ok := pcu.mutation.BatchConfig(); ok {
		_spec.SetField(partnerconfig.FieldBatchConfig, field.TypeJSON, value)
	}
	if pcu.mutation.BatchConfigCleared() {
		_spec.ClearField(partnerconfig.FieldBatchConfig, field.TypeJSON)
	}
	if value, ok := pcu.mutation.RateLimits(); ok {
		_spec.SetField(partnerconfig.FieldRateLimits, field.TypeJSON, value)
	}
	if pcu.mutation.RateLimitsCleared() {
		_spec.ClearField(partnerconfig.FieldRateLimits, field.TypeJSON)
	}
	if value, ok := pcu.mutation.Enabled(); ok {
		_spec.SetField(partnerconfig.FieldEnabled, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pcu.mutation.done = true
	return n, nil
}

// PartnerConfigUpdateOne is the builder for updating a single PartnerConfig entity.
type PartnerConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PartnerConfigMutation
}

// SetUpdateTime sets the "update_time" field.
func (pcuo *PartnerConfigUpdateOne) SetUpdateTime(t time.Time) *PartnerConfigUpdateOne {
	pcuo.mutation.SetUpdateTime(t)
	return pcuo
}

// SetTenantID sets the "tenant_id" field.
func (pcuo *PartnerConfigUpdateOne) SetTenantID(i int64) *PartnerConfigUpdateOne {
	pcuo.mutation.ResetTenantID()
	pcuo.mutation.SetTenantID(i)
	return pcuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pcuo *PartnerConfigUpdateOne) SetNillableTenantID(i *int64) *PartnerConfigUpdateOne {
	if i != nil {
		pcuo.SetTenantID(*i)
	}
	return pcuo
}

// AddTenantID adds i to the "tenant_id" field.
func (pcuo *PartnerConfigUpdateOne) AddTenantID(i int64) *PartnerConfigUpdateOne {
	pcuo.mutation.AddTenantID(i)
	return pcuo
}

// SetEmailProviders sets the "email_providers" field.
func (pcuo *PartnerConfigUpdateOne) SetEmailProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.SetEmailProviders(sc)
	return pcuo
}

// AppendEmailProviders appends sc to the "email_providers" field.
func (pcuo *PartnerConfigUpdateOne) AppendEmailProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.AppendEmailProviders(sc)
	return pcuo
}

// ClearEmailProviders clears the value of the "email_providers" field.
func (pcuo *PartnerConfigUpdateOne) ClearEmailProviders() *PartnerConfigUpdateOne {
	pcuo.mutation.ClearEmailProviders()
	return pcuo
}

// SetSmsProviders sets the "sms_providers" field.
func (pcuo *PartnerConfigUpdateOne) SetSmsProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.SetSmsProviders(sc)
	return pcuo
}

// AppendSmsProviders appends sc to the "sms_providers" field.
func (pcuo *PartnerConfigUpdateOne) AppendSmsProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.AppendSmsProviders(sc)
	return pcuo
}

// ClearSmsProviders clears the value of the "sms_providers" field.
func (pcuo *PartnerConfigUpdateOne) ClearSmsProviders() *PartnerConfigUpdateOne {
	pcuo.mutation.ClearSmsProviders()
	return pcuo
}

// SetPushProviders sets the "push_providers" field.
func (pcuo *PartnerConfigUpdateOne) SetPushProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.SetPushProviders(sc)
	return pcuo
}

// AppendPushProviders appends sc to the "push_providers" field.
func (pcuo *PartnerConfigUpdateOne) AppendPushProviders(sc []schema.ProviderConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.AppendPushProviders(sc)
	return pcuo
}

// ClearPushProviders clears the value of the "push_providers" field.
func (pcuo *PartnerConfigUpdateOne) ClearPushProviders() *PartnerConfigUpdateOne {
	pcuo.mutation.ClearPushProviders()
	return pcuo
}

// SetBatchConfig sets the "batch_config" field.
func (pcuo *PartnerConfigUpdateOne) SetBatchConfig(sc *schema.BatchConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.SetBatchConfig(sc)
	return pcuo
}

// ClearBatchConfig clears the value of the "batch_config" field.
func (pcuo *PartnerConfigUpdateOne) ClearBatchConfig() *PartnerConfigUpdateOne {
	pcuo.mutation.ClearBatchConfig()
	return pcuo
}

// SetRateLimits sets the "rate_limits" field.
func (pcuo *PartnerConfigUpdateOne) SetRateLimits(ml map[string]schema.RateLimit) *PartnerConfigUpdateOne {
	pcuo.mutation.SetRateLimits(ml)
	return pcuo
}

// ClearRateLimits clears the value of the "rate_limits" field.
func (pcuo *PartnerConfigUpdateOne) ClearRateLimits() *PartnerConfigUpdateOne {
	pcuo.mutation.ClearRateLimits()
	return pcuo
}

// SetEnabled sets the "enabled" field.
func (pcuo *PartnerConfigUpdateOne) SetEnabled(b bool) *PartnerConfigUpdateOne {
	pcuo.mutation.SetEnabled(b)
	return pcuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (pcuo *PartnerConfigUpdateOne) SetNillableEnabled(b *bool) *PartnerConfigUpdateOne {
	if b != nil {
		pcuo.SetEnabled(*b)
	}
	return pcuo
}

// Mutation returns the PartnerConfigMutation object of the builder.
func (pcuo *PartnerConfigUpdateOne) Mutation() *PartnerConfigMutation {
	return pcuo.mutation
}

// Where appends a list predicates to the PartnerConfigUpdate builder.
func (pcuo *PartnerConfigUpdateOne) Where(ps ...predicate.PartnerConfig) *PartnerConfigUpdateOne {
	pcuo.mutation.Where(ps...)
	return pcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pcuo *PartnerConfigUpdateOne) Select(field string, fields ...string) *PartnerConfigUpdateOne {
	pcuo.fields = append([]string{field}, fields...)
	return pcuo
}

// Save executes the query and returns the updated PartnerConfig entity.
func (pcuo *PartnerConfigUpdateOne) Save(ctx context.Context) (*PartnerConfig, error) {
	pcuo.defaults()
	return withHooks(ctx, pcuo.sqlSave, pcuo.mutation, pcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pcuo *PartnerConfigUpdateOne) SaveX(ctx context.Context) *PartnerConfig {
	node, err := pcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pcuo *PartnerConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := pcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcuo *PartnerConfigUpdateOne) ExecX(ctx context.Context) {
	if err := pcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcuo *PartnerConfigUpdateOne) defaults() {
	if _, ok := pcuo.mutation.UpdateTime(); !ok {
		v := partnerconfig.UpdateDefaultUpdateTime()
		pcuo.mutation.SetUpdateTime(v)
	}
}

func (pcuo *PartnerConfigUpdateOne) sqlSave(ctx context.Context) (_node *PartnerConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(partnerconfig.Table, partnerconfig.Columns, sqlgraph.NewFieldSpec(partnerconfig.FieldID, field.TypeString))
	id, ok := pcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PartnerConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerconfig.FieldID)
		for _, f := range fields {
			if !partnerconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != partnerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcuo.mutation.UpdateTime(); ok {
		_spec.SetField(partnerconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pcuo.mutation.TenantID(); ok {
		_spec.SetField(partnerconfig.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := pcuo.mutation.AddedTenantID(); ok {
		_spec.AddField(partnerconfig.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := pcuo.mutation.EmailProviders(); ok {
		_spec.SetField(partnerconfig.FieldEmailProviders, field.TypeJSON, value)
	}
	if value, ok := pcuo.mutation.AppendedEmailProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldEmailProviders, value)
		})
	}
	if pcuo.mutation.EmailProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldEmailProviders, field.TypeJSON)
	}
	if value, ok := pcuo.mutation.SmsProviders(); ok {
		_spec.SetField(partnerconfig.FieldSmsProviders, field.TypeJSON, value)
	}
	if value, ok := pcuo.mutation.AppendedSmsProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldSmsProviders, value)
		})
	}
	if pcuo.mutation.SmsProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldSmsProviders, field.TypeJSON)
	}
	if value, ok := pcuo.mutation.PushProviders(); ok {
		_spec.SetField(partnerconfig.FieldPushProviders, field.TypeJSON, value)
	}
	if value, ok := pcuo.mutation.AppendedPushProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, partnerconfig.FieldPushProviders, value)
		})
	}
	if pcuo.mutation.PushProvidersCleared() {
		_spec.ClearField(partnerconfig.FieldPushProviders, field.TypeJSON)
	}
	if value, ok := pcuo.mutation.BatchConfig(); ok {
		_spec.SetField(partnerconfig.FieldBatchConfig, field.TypeJSON, value)
	}
	if pcuo.mutation.BatchConfigCleared() {
		_spec.ClearField(partnerconfig.FieldBatchConfig, field.TypeJSON)
	}
	if value, ok := pcuo.mutation.RateLimits(); ok {
		_spec.SetField(partnerconfig.FieldRateLimits, field.TypeJSON, value)
	}
	if pcuo.mutation.RateLimitsCleared() {
		_spec.ClearField(partnerconfig.FieldRateLimits, field.TypeJSON)
	}
	if value, ok := pcuo.mutation.Enabled(); ok {
		_spec.SetField(partnerconfig.FieldEnabled, field.TypeBool, value)
	}
	_node = &PartnerConfig{config: pcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pcuo.mutation.done = true
	return _node, nil
}
