// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.smartbet.am/golang/notification/ent/partnerconfig"
	"gitlab.smartbet.am/golang/notification/ent/predicate"
)

// PartnerConfigQuery is the builder for querying PartnerConfig entities.
type PartnerConfigQuery struct {
	config
	ctx        *QueryContext
	order      []partnerconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.PartnerConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PartnerConfigQuery builder.
func (pcq *PartnerConfigQuery) Where(ps ...predicate.PartnerConfig) *PartnerConfigQuery {
	pcq.predicates = append(pcq.predicates, ps...)
	return pcq
}

// Limit the number of records to be returned by this query.
func (pcq *PartnerConfigQuery) Limit(limit int) *PartnerConfigQuery {
	pcq.ctx.Limit = &limit
	return pcq
}

// Offset to start from.
func (pcq *PartnerConfigQuery) Offset(offset int) *PartnerConfigQuery {
	pcq.ctx.Offset = &offset
	return pcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcq *PartnerConfigQuery) Unique(unique bool) *PartnerConfigQuery {
	pcq.ctx.Unique = &unique
	return pcq
}

// Order specifies how the records should be ordered.
func (pcq *PartnerConfigQuery) Order(o ...partnerconfig.OrderOption) *PartnerConfigQuery {
	pcq.order = append(pcq.order, o...)
	return pcq
}

// First returns the first PartnerConfig entity from the query.
// Returns a *NotFoundError when no PartnerConfig was found.
func (pcq *PartnerConfigQuery) First(ctx context.Context) (*PartnerConfig, error) {
	nodes, err := pcq.Limit(1).All(setContextOp(ctx, pcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{partnerconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcq *PartnerConfigQuery) FirstX(ctx context.Context) *PartnerConfig {
	node, err := pcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PartnerConfig ID from the query.
// Returns a *NotFoundError when no PartnerConfig ID was found.
func (pcq *PartnerConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pcq.Limit(1).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{partnerconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcq *PartnerConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := pcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PartnerConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PartnerConfig entity is found.
// Returns a *NotFoundError when no PartnerConfig entities are found.
func (pcq *PartnerConfigQuery) Only(ctx context.Context) (*PartnerConfig, error) {
	nodes, err := pcq.Limit(2).All(setContextOp(ctx, pcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{partnerconfig.Label}
	default:
		return nil, &NotSingularError{partnerconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcq *PartnerConfigQuery) OnlyX(ctx context.Context) *PartnerConfig {
	node, err := pcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PartnerConfig ID in the query.
// Returns a *NotSingularError when more than one PartnerConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcq *PartnerConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pcq.Limit(2).IDs(setContextOp(ctx, pcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{partnerconfig.Label}
	default:
		err = &NotSingularError{partnerconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcq *PartnerConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := pcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PartnerConfigs.
func (pcq *PartnerConfigQuery) All(ctx context.Context) ([]*PartnerConfig, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryAll)
	if err := pcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PartnerConfig, *PartnerConfigQuery]()
	return withInterceptors[[]*PartnerConfig](ctx, pcq, qr, pcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pcq *PartnerConfigQuery) AllX(ctx context.Context) []*PartnerConfig {
	nodes, err := pcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PartnerConfig IDs.
func (pcq *PartnerConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pcq.ctx.Unique == nil && pcq.path != nil {
		pcq.Unique(true)
	}
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryIDs)
	if err = pcq.Select(partnerconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcq *PartnerConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := pcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcq *PartnerConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryCount)
	if err := pcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pcq, querierCount[*PartnerConfigQuery](), pcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pcq *PartnerConfigQuery) CountX(ctx context.Context) int {
	count, err := pcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcq *PartnerConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pcq.ctx, ent.OpQueryExist)
	switch _, err := pcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pcq *PartnerConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := pcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PartnerConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcq *PartnerConfigQuery) Clone() *PartnerConfigQuery {
	if pcq == nil {
		return nil
	}
	return &PartnerConfigQuery{
		config:     pcq.config,
		ctx:        pcq.ctx.Clone(),
		order:      append([]partnerconfig.OrderOption{}, pcq.order...),
		inters:     append([]Interceptor{}, pcq.inters...),
		predicates: append([]predicate.PartnerConfig{}, pcq.predicates...),
		// clone intermediate query.
		sql:  pcq.sql.Clone(),
		path: pcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PartnerConfig.Query().
//		GroupBy(partnerconfig.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pcq *PartnerConfigQuery) GroupBy(field string, fields ...string) *PartnerConfigGroupBy {
	pcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PartnerConfigGroupBy{build: pcq}
	grbuild.flds = &pcq.ctx.Fields
	grbuild.label = partnerconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.PartnerConfig.Query().
//		Select(partnerconfig.FieldCreateTime).
//		Scan(ctx, &v)
func (pcq *PartnerConfigQuery) Select(fields ...string) *PartnerConfigSelect {
	pcq.ctx.Fields = append(pcq.ctx.Fields, fields...)
	sbuild := &PartnerConfigSelect{PartnerConfigQuery: pcq}
	sbuild.label = partnerconfig.Label
	sbuild.flds, sbuild.scan = &pcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PartnerConfigSelect configured with the given aggregations.
func (pcq *PartnerConfigQuery) Aggregate(fns ...AggregateFunc) *PartnerConfigSelect {
	return pcq.Select().Aggregate(fns...)
}

func (pcq *PartnerConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pcq); err != nil {
				return err
			}
		}
	}
	for _, f := range pcq.ctx.Fields {
		if !partnerconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcq.path != nil {
		prev, err := pcq.path(ctx)
		if err != nil {
			return err
		}
		pcq.sql = prev
	}
	return nil
}

func (pcq *PartnerConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PartnerConfig, error) {
	var (
		nodes = []*PartnerConfig{}
		_spec = pcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PartnerConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PartnerConfig{config: pcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pcq *PartnerConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcq.querySpec()
	_spec.Node.Columns = pcq.ctx.Fields
	if len(pcq.ctx.Fields) > 0 {
		_spec.Unique = pcq.ctx.Unique != nil && *pcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pcq.driver, _spec)
}

func (pcq *PartnerConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(partnerconfig.Table, partnerconfig.Columns, sqlgraph.NewFieldSpec(partnerconfig.FieldID, field.TypeString))
	_spec.From = pcq.sql
	if unique := pcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pcq.path != nil {
		_spec.Unique = true
	}
	if fields := pcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerconfig.FieldID)
		for i := range fields {
			if fields[i] != partnerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcq *PartnerConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcq.driver.Dialect())
	t1 := builder.Table(partnerconfig.Table)
	columns := pcq.ctx.Fields
	if len(columns) == 0 {
		columns = partnerconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcq.sql != nil {
		selector = pcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcq.ctx.Unique != nil && *pcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pcq.predicates {
		p(selector)
	}
	for _, p := range pcq.order {
		p(selector)
	}
	if offset := pcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PartnerConfigGroupBy is the group-by builder for PartnerConfig entities.
type PartnerConfigGroupBy struct {
	selector
	build *PartnerConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcgb *PartnerConfigGroupBy) Aggregate(fns ...AggregateFunc) *PartnerConfigGroupBy {
	pcgb.fns = append(pcgb.fns, fns...)
	return pcgb
}

// Scan applies the selector query and scans the result into the given value.
func (pcgb *PartnerConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcgb.build.ctx, ent.OpQueryGroupBy)
	if err := pcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerConfigQuery, *PartnerConfigGroupBy](ctx, pcgb.build, pcgb, pcgb.build.inters, v)
}

func (pcgb *PartnerConfigGroupBy) sqlScan(ctx context.Context, root *PartnerConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pcgb.fns))
	for _, fn := range pcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pcgb.flds)+len(pcgb.fns))
		for _, f := range *pcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PartnerConfigSelect is the builder for selecting fields of PartnerConfig entities.
type PartnerConfigSelect struct {
	*PartnerConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pcs *PartnerConfigSelect) Aggregate(fns ...AggregateFunc) *PartnerConfigSelect {
	pcs.fns = append(pcs.fns, fns...)
	return pcs
}

// Scan applies the selector query and scans the result into the given value.
func (pcs *PartnerConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pcs.ctx, ent.OpQuerySelect)
	if err := pcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartnerConfigQuery, *PartnerConfigSelect](ctx, pcs.PartnerConfigQuery, pcs, pcs.inters, v)
}

func (pcs *PartnerConfigSelect) sqlScan(ctx context.Context, root *PartnerConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pcs.fns))
	for _, fn := range pcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
