// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.com/healthcare-integration/golang/notification-service/ent/notification"
	"gitlab.com/healthcare-integration/golang/notification-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinFields0 := notificationMixin[0].Fields()
	_ = notificationMixinFields0
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreateTime is the schema descriptor for create_time field.
	notificationDescCreateTime := notificationMixinFields0[0].Descriptor()
	// notification.DefaultCreateTime holds the default value on creation for the create_time field.
	notification.DefaultCreateTime = notificationDescCreateTime.Default.(func() time.Time)
	// notificationDescUpdateTime is the schema descriptor for update_time field.
	notificationDescUpdateTime := notificationMixinFields0[1].Descriptor()
	// notification.DefaultUpdateTime holds the default value on creation for the update_time field.
	notification.DefaultUpdateTime = notificationDescUpdateTime.Default.(func() time.Time)
	// notification.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	notification.UpdateDefaultUpdateTime = notificationDescUpdateTime.UpdateDefault.(func() time.Time)
}
