// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.smartbet.am/golang/notification/ent/notification"
	"gitlab.smartbet.am/golang/notification/ent/partnerconfig"
	"gitlab.smartbet.am/golang/notification/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinFields0 := notificationMixin[0].Fields()
	_ = notificationMixinFields0
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreateTime is the schema descriptor for create_time field.
	notificationDescCreateTime := notificationMixinFields0[0].Descriptor()
	// notification.DefaultCreateTime holds the default value on creation for the create_time field.
	notification.DefaultCreateTime = notificationDescCreateTime.Default.(func() time.Time)
	// notificationDescUpdateTime is the schema descriptor for update_time field.
	notificationDescUpdateTime := notificationMixinFields0[1].Descriptor()
	// notification.DefaultUpdateTime holds the default value on creation for the update_time field.
	notification.DefaultUpdateTime = notificationDescUpdateTime.Default.(func() time.Time)
	// notification.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	notification.UpdateDefaultUpdateTime = notificationDescUpdateTime.UpdateDefault.(func() time.Time)
	// notificationDescRetryCount is the schema descriptor for retry_count field.
	notificationDescRetryCount := notificationFields[15].Descriptor()
	// notification.DefaultRetryCount holds the default value on creation for the retry_count field.
	notification.DefaultRetryCount = notificationDescRetryCount.Default.(int)
	partnerconfigMixin := schema.PartnerConfig{}.Mixin()
	partnerconfigMixinFields0 := partnerconfigMixin[0].Fields()
	_ = partnerconfigMixinFields0
	partnerconfigFields := schema.PartnerConfig{}.Fields()
	_ = partnerconfigFields
	// partnerconfigDescCreateTime is the schema descriptor for create_time field.
	partnerconfigDescCreateTime := partnerconfigMixinFields0[0].Descriptor()
	// partnerconfig.DefaultCreateTime holds the default value on creation for the create_time field.
	partnerconfig.DefaultCreateTime = partnerconfigDescCreateTime.Default.(func() time.Time)
	// partnerconfigDescUpdateTime is the schema descriptor for update_time field.
	partnerconfigDescUpdateTime := partnerconfigMixinFields0[1].Descriptor()
	// partnerconfig.DefaultUpdateTime holds the default value on creation for the update_time field.
	partnerconfig.DefaultUpdateTime = partnerconfigDescUpdateTime.Default.(func() time.Time)
	// partnerconfig.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	partnerconfig.UpdateDefaultUpdateTime = partnerconfigDescUpdateTime.UpdateDefault.(func() time.Time)
	// partnerconfigDescEnabled is the schema descriptor for enabled field.
	partnerconfigDescEnabled := partnerconfigFields[7].Descriptor()
	// partnerconfig.DefaultEnabled holds the default value on creation for the enabled field.
	partnerconfig.DefaultEnabled = partnerconfigDescEnabled.Default.(bool)
	// partnerconfigDescID is the schema descriptor for id field.
	partnerconfigDescID := partnerconfigFields[0].Descriptor()
	// partnerconfig.DefaultID holds the default value on creation for the id field.
	partnerconfig.DefaultID = partnerconfigDescID.Default.(string)
}
