// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: storage/config.proto

package storage

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ConfigService service

func NewConfigServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ConfigService service

type ConfigService interface {
	SetTenantAppointmentTypeStatus(ctx context.Context, in *TenantAppointmentTypeStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	GetTenantAppointmentTypes(ctx context.Context, in *TenantAppointmentTypesRequest, opts ...client.CallOption) (*TenantAppointmentTypesResponse, error)
}

type configService struct {
	c    client.Client
	name string
}

func NewConfigService(name string, c client.Client) ConfigService {
	return &configService{
		c:    c,
		name: name,
	}
}

func (c *configService) SetTenantAppointmentTypeStatus(ctx context.Context, in *TenantAppointmentTypeStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "ConfigService.SetTenantAppointmentTypeStatus", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) GetTenantAppointmentTypes(ctx context.Context, in *TenantAppointmentTypesRequest, opts ...client.CallOption) (*TenantAppointmentTypesResponse, error) {
	req := c.c.NewRequest(c.name, "ConfigService.GetTenantAppointmentTypes", in)
	out := new(TenantAppointmentTypesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConfigService service

type ConfigServiceHandler interface {
	SetTenantAppointmentTypeStatus(context.Context, *TenantAppointmentTypeStatusRequest, *emptypb.Empty) error
	GetTenantAppointmentTypes(context.Context, *TenantAppointmentTypesRequest, *TenantAppointmentTypesResponse) error
}

func RegisterConfigServiceHandler(s server.Server, hdlr ConfigServiceHandler, opts ...server.HandlerOption) error {
	type configService interface {
		SetTenantAppointmentTypeStatus(ctx context.Context, in *TenantAppointmentTypeStatusRequest, out *emptypb.Empty) error
		GetTenantAppointmentTypes(ctx context.Context, in *TenantAppointmentTypesRequest, out *TenantAppointmentTypesResponse) error
	}
	type ConfigService struct {
		configService
	}
	h := &configServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ConfigService{h}, opts...))
}

type configServiceHandler struct {
	ConfigServiceHandler
}

func (h *configServiceHandler) SetTenantAppointmentTypeStatus(ctx context.Context, in *TenantAppointmentTypeStatusRequest, out *emptypb.Empty) error {
	return h.ConfigServiceHandler.SetTenantAppointmentTypeStatus(ctx, in, out)
}

func (h *configServiceHandler) GetTenantAppointmentTypes(ctx context.Context, in *TenantAppointmentTypesRequest, out *TenantAppointmentTypesResponse) error {
	return h.ConfigServiceHandler.GetTenantAppointmentTypes(ctx, in, out)
}
