// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: storage/storage.proto

package storage

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StorageService service

func NewStorageServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StorageService service

type StorageService interface {
	SyncProviders(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error)
	SyncDepartments(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error)
	SyncOpenAppointments(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error)
	SyncAppointmentTypes(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error)
	ProviderList(ctx context.Context, in *Tenant, opts ...client.CallOption) (*ProviderListResponse, error)
	DepartmentList(ctx context.Context, in *Tenant, opts ...client.CallOption) (*DepartmentListResponse, error)
	NextAvailable(ctx context.Context, in *NextAvailableRequest, opts ...client.CallOption) (*Appointment, error)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...client.CallOption) (*AppointmentList, error)
	GetScheduleGroup(ctx context.Context, in *GetScheduleRequest, opts ...client.CallOption) (*AppointmentList, error)
	SetAppointmentLockStatus(ctx context.Context, in *SetAppointmentLockStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	GetPrevAppointment(ctx context.Context, in *PrevAppointmentRequest, opts ...client.CallOption) (*Appointment, error)
	GetNextAppointment(ctx context.Context, in *NextAppointmentRequest, opts ...client.CallOption) (*Appointment, error)
	GetAppointment(ctx context.Context, in *AppointmentRequest, opts ...client.CallOption) (*Appointment, error)
	SetAppointmentInternalStatus(ctx context.Context, in *InternalStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	NextAvailableDepartmentList(ctx context.Context, in *NextAvailableDepartmentListRequest, opts ...client.CallOption) (*AppointmentList, error)
	NextAvailableProviderList(ctx context.Context, in *NextAvailableProviderListRequest, opts ...client.CallOption) (*AppointmentList, error)
	UpdateAppointmentType(ctx context.Context, in *UpdateAppointmentTypeRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	GetProvider(ctx context.Context, in *ProviderRequest, opts ...client.CallOption) (*Provider, error)
	GetDepartment(ctx context.Context, in *DepartmentRequest, opts ...client.CallOption) (*Department, error)
	SetDepartmentActiveState(ctx context.Context, in *DepartmentActiveStateRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	SetProviderActiveState(ctx context.Context, in *ProviderActiveStateRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	SetTenantCronJob(ctx context.Context, in *TenantCronJobRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	SetTenantCronJobStatus(ctx context.Context, in *TenantCronJobStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	GetTenantCronJob(ctx context.Context, in *Tenant, opts ...client.CallOption) (*TenantCronJob, error)
	GetProviderDepartmentsRange(ctx context.Context, in *ProviderDepartmentsRangeRequest, opts ...client.CallOption) (*ProviderDepartmentsRangeResponse, error)
	GetDepartmentProvidersRange(ctx context.Context, in *DepartmentProvidersRangeRequest, opts ...client.CallOption) (*DepartmentProvidersRangeResponse, error)
	SetProviderVisitType(ctx context.Context, in *ProviderVisitTypeRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...client.CallOption) (*emptypb.Empty, error)
}

type storageService struct {
	c    client.Client
	name string
}

func NewStorageService(name string, c client.Client) StorageService {
	return &storageService{
		c:    c,
		name: name,
	}
}

func (c *storageService) SyncProviders(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SyncProviders", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SyncDepartments(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SyncDepartments", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SyncOpenAppointments(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SyncOpenAppointments", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SyncAppointmentTypes(ctx context.Context, in *Tenant, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SyncAppointmentTypes", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) ProviderList(ctx context.Context, in *Tenant, opts ...client.CallOption) (*ProviderListResponse, error) {
	req := c.c.NewRequest(c.name, "StorageService.ProviderList", in)
	out := new(ProviderListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) DepartmentList(ctx context.Context, in *Tenant, opts ...client.CallOption) (*DepartmentListResponse, error) {
	req := c.c.NewRequest(c.name, "StorageService.DepartmentList", in)
	out := new(DepartmentListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) NextAvailable(ctx context.Context, in *NextAvailableRequest, opts ...client.CallOption) (*Appointment, error) {
	req := c.c.NewRequest(c.name, "StorageService.NextAvailable", in)
	out := new(Appointment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...client.CallOption) (*AppointmentList, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetSchedule", in)
	out := new(AppointmentList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetScheduleGroup(ctx context.Context, in *GetScheduleRequest, opts ...client.CallOption) (*AppointmentList, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetScheduleGroup", in)
	out := new(AppointmentList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetAppointmentLockStatus(ctx context.Context, in *SetAppointmentLockStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetAppointmentLockStatus", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetPrevAppointment(ctx context.Context, in *PrevAppointmentRequest, opts ...client.CallOption) (*Appointment, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetPrevAppointment", in)
	out := new(Appointment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetNextAppointment(ctx context.Context, in *NextAppointmentRequest, opts ...client.CallOption) (*Appointment, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetNextAppointment", in)
	out := new(Appointment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetAppointment(ctx context.Context, in *AppointmentRequest, opts ...client.CallOption) (*Appointment, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetAppointment", in)
	out := new(Appointment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetAppointmentInternalStatus(ctx context.Context, in *InternalStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetAppointmentInternalStatus", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) NextAvailableDepartmentList(ctx context.Context, in *NextAvailableDepartmentListRequest, opts ...client.CallOption) (*AppointmentList, error) {
	req := c.c.NewRequest(c.name, "StorageService.NextAvailableDepartmentList", in)
	out := new(AppointmentList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) NextAvailableProviderList(ctx context.Context, in *NextAvailableProviderListRequest, opts ...client.CallOption) (*AppointmentList, error) {
	req := c.c.NewRequest(c.name, "StorageService.NextAvailableProviderList", in)
	out := new(AppointmentList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) UpdateAppointmentType(ctx context.Context, in *UpdateAppointmentTypeRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.UpdateAppointmentType", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetProvider(ctx context.Context, in *ProviderRequest, opts ...client.CallOption) (*Provider, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetProvider", in)
	out := new(Provider)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetDepartment(ctx context.Context, in *DepartmentRequest, opts ...client.CallOption) (*Department, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetDepartment", in)
	out := new(Department)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetDepartmentActiveState(ctx context.Context, in *DepartmentActiveStateRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetDepartmentActiveState", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetProviderActiveState(ctx context.Context, in *ProviderActiveStateRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetProviderActiveState", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetTenantCronJob(ctx context.Context, in *TenantCronJobRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetTenantCronJob", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetTenantCronJobStatus(ctx context.Context, in *TenantCronJobStatusRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetTenantCronJobStatus", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetTenantCronJob(ctx context.Context, in *Tenant, opts ...client.CallOption) (*TenantCronJob, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetTenantCronJob", in)
	out := new(TenantCronJob)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetProviderDepartmentsRange(ctx context.Context, in *ProviderDepartmentsRangeRequest, opts ...client.CallOption) (*ProviderDepartmentsRangeResponse, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetProviderDepartmentsRange", in)
	out := new(ProviderDepartmentsRangeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) GetDepartmentProvidersRange(ctx context.Context, in *DepartmentProvidersRangeRequest, opts ...client.CallOption) (*DepartmentProvidersRangeResponse, error) {
	req := c.c.NewRequest(c.name, "StorageService.GetDepartmentProvidersRange", in)
	out := new(DepartmentProvidersRangeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) SetProviderVisitType(ctx context.Context, in *ProviderVisitTypeRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.SetProviderVisitType", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageService) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "StorageService.UpdateProvider", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StorageService service

type StorageServiceHandler interface {
	SyncProviders(context.Context, *Tenant, *emptypb.Empty) error
	SyncDepartments(context.Context, *Tenant, *emptypb.Empty) error
	SyncOpenAppointments(context.Context, *Tenant, *emptypb.Empty) error
	SyncAppointmentTypes(context.Context, *Tenant, *emptypb.Empty) error
	ProviderList(context.Context, *Tenant, *ProviderListResponse) error
	DepartmentList(context.Context, *Tenant, *DepartmentListResponse) error
	NextAvailable(context.Context, *NextAvailableRequest, *Appointment) error
	GetSchedule(context.Context, *GetScheduleRequest, *AppointmentList) error
	GetScheduleGroup(context.Context, *GetScheduleRequest, *AppointmentList) error
	SetAppointmentLockStatus(context.Context, *SetAppointmentLockStatusRequest, *emptypb.Empty) error
	GetPrevAppointment(context.Context, *PrevAppointmentRequest, *Appointment) error
	GetNextAppointment(context.Context, *NextAppointmentRequest, *Appointment) error
	GetAppointment(context.Context, *AppointmentRequest, *Appointment) error
	SetAppointmentInternalStatus(context.Context, *InternalStatusRequest, *emptypb.Empty) error
	NextAvailableDepartmentList(context.Context, *NextAvailableDepartmentListRequest, *AppointmentList) error
	NextAvailableProviderList(context.Context, *NextAvailableProviderListRequest, *AppointmentList) error
	UpdateAppointmentType(context.Context, *UpdateAppointmentTypeRequest, *emptypb.Empty) error
	GetProvider(context.Context, *ProviderRequest, *Provider) error
	GetDepartment(context.Context, *DepartmentRequest, *Department) error
	SetDepartmentActiveState(context.Context, *DepartmentActiveStateRequest, *emptypb.Empty) error
	SetProviderActiveState(context.Context, *ProviderActiveStateRequest, *emptypb.Empty) error
	SetTenantCronJob(context.Context, *TenantCronJobRequest, *emptypb.Empty) error
	SetTenantCronJobStatus(context.Context, *TenantCronJobStatusRequest, *emptypb.Empty) error
	GetTenantCronJob(context.Context, *Tenant, *TenantCronJob) error
	GetProviderDepartmentsRange(context.Context, *ProviderDepartmentsRangeRequest, *ProviderDepartmentsRangeResponse) error
	GetDepartmentProvidersRange(context.Context, *DepartmentProvidersRangeRequest, *DepartmentProvidersRangeResponse) error
	SetProviderVisitType(context.Context, *ProviderVisitTypeRequest, *emptypb.Empty) error
	UpdateProvider(context.Context, *UpdateProviderRequest, *emptypb.Empty) error
}

func RegisterStorageServiceHandler(s server.Server, hdlr StorageServiceHandler, opts ...server.HandlerOption) error {
	type storageService interface {
		SyncProviders(ctx context.Context, in *Tenant, out *emptypb.Empty) error
		SyncDepartments(ctx context.Context, in *Tenant, out *emptypb.Empty) error
		SyncOpenAppointments(ctx context.Context, in *Tenant, out *emptypb.Empty) error
		SyncAppointmentTypes(ctx context.Context, in *Tenant, out *emptypb.Empty) error
		ProviderList(ctx context.Context, in *Tenant, out *ProviderListResponse) error
		DepartmentList(ctx context.Context, in *Tenant, out *DepartmentListResponse) error
		NextAvailable(ctx context.Context, in *NextAvailableRequest, out *Appointment) error
		GetSchedule(ctx context.Context, in *GetScheduleRequest, out *AppointmentList) error
		GetScheduleGroup(ctx context.Context, in *GetScheduleRequest, out *AppointmentList) error
		SetAppointmentLockStatus(ctx context.Context, in *SetAppointmentLockStatusRequest, out *emptypb.Empty) error
		GetPrevAppointment(ctx context.Context, in *PrevAppointmentRequest, out *Appointment) error
		GetNextAppointment(ctx context.Context, in *NextAppointmentRequest, out *Appointment) error
		GetAppointment(ctx context.Context, in *AppointmentRequest, out *Appointment) error
		SetAppointmentInternalStatus(ctx context.Context, in *InternalStatusRequest, out *emptypb.Empty) error
		NextAvailableDepartmentList(ctx context.Context, in *NextAvailableDepartmentListRequest, out *AppointmentList) error
		NextAvailableProviderList(ctx context.Context, in *NextAvailableProviderListRequest, out *AppointmentList) error
		UpdateAppointmentType(ctx context.Context, in *UpdateAppointmentTypeRequest, out *emptypb.Empty) error
		GetProvider(ctx context.Context, in *ProviderRequest, out *Provider) error
		GetDepartment(ctx context.Context, in *DepartmentRequest, out *Department) error
		SetDepartmentActiveState(ctx context.Context, in *DepartmentActiveStateRequest, out *emptypb.Empty) error
		SetProviderActiveState(ctx context.Context, in *ProviderActiveStateRequest, out *emptypb.Empty) error
		SetTenantCronJob(ctx context.Context, in *TenantCronJobRequest, out *emptypb.Empty) error
		SetTenantCronJobStatus(ctx context.Context, in *TenantCronJobStatusRequest, out *emptypb.Empty) error
		GetTenantCronJob(ctx context.Context, in *Tenant, out *TenantCronJob) error
		GetProviderDepartmentsRange(ctx context.Context, in *ProviderDepartmentsRangeRequest, out *ProviderDepartmentsRangeResponse) error
		GetDepartmentProvidersRange(ctx context.Context, in *DepartmentProvidersRangeRequest, out *DepartmentProvidersRangeResponse) error
		SetProviderVisitType(ctx context.Context, in *ProviderVisitTypeRequest, out *emptypb.Empty) error
		UpdateProvider(ctx context.Context, in *UpdateProviderRequest, out *emptypb.Empty) error
	}
	type StorageService struct {
		storageService
	}
	h := &storageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StorageService{h}, opts...))
}

type storageServiceHandler struct {
	StorageServiceHandler
}

func (h *storageServiceHandler) SyncProviders(ctx context.Context, in *Tenant, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SyncProviders(ctx, in, out)
}

func (h *storageServiceHandler) SyncDepartments(ctx context.Context, in *Tenant, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SyncDepartments(ctx, in, out)
}

func (h *storageServiceHandler) SyncOpenAppointments(ctx context.Context, in *Tenant, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SyncOpenAppointments(ctx, in, out)
}

func (h *storageServiceHandler) SyncAppointmentTypes(ctx context.Context, in *Tenant, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SyncAppointmentTypes(ctx, in, out)
}

func (h *storageServiceHandler) ProviderList(ctx context.Context, in *Tenant, out *ProviderListResponse) error {
	return h.StorageServiceHandler.ProviderList(ctx, in, out)
}

func (h *storageServiceHandler) DepartmentList(ctx context.Context, in *Tenant, out *DepartmentListResponse) error {
	return h.StorageServiceHandler.DepartmentList(ctx, in, out)
}

func (h *storageServiceHandler) NextAvailable(ctx context.Context, in *NextAvailableRequest, out *Appointment) error {
	return h.StorageServiceHandler.NextAvailable(ctx, in, out)
}

func (h *storageServiceHandler) GetSchedule(ctx context.Context, in *GetScheduleRequest, out *AppointmentList) error {
	return h.StorageServiceHandler.GetSchedule(ctx, in, out)
}

func (h *storageServiceHandler) GetScheduleGroup(ctx context.Context, in *GetScheduleRequest, out *AppointmentList) error {
	return h.StorageServiceHandler.GetScheduleGroup(ctx, in, out)
}

func (h *storageServiceHandler) SetAppointmentLockStatus(ctx context.Context, in *SetAppointmentLockStatusRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetAppointmentLockStatus(ctx, in, out)
}

func (h *storageServiceHandler) GetPrevAppointment(ctx context.Context, in *PrevAppointmentRequest, out *Appointment) error {
	return h.StorageServiceHandler.GetPrevAppointment(ctx, in, out)
}

func (h *storageServiceHandler) GetNextAppointment(ctx context.Context, in *NextAppointmentRequest, out *Appointment) error {
	return h.StorageServiceHandler.GetNextAppointment(ctx, in, out)
}

func (h *storageServiceHandler) GetAppointment(ctx context.Context, in *AppointmentRequest, out *Appointment) error {
	return h.StorageServiceHandler.GetAppointment(ctx, in, out)
}

func (h *storageServiceHandler) SetAppointmentInternalStatus(ctx context.Context, in *InternalStatusRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetAppointmentInternalStatus(ctx, in, out)
}

func (h *storageServiceHandler) NextAvailableDepartmentList(ctx context.Context, in *NextAvailableDepartmentListRequest, out *AppointmentList) error {
	return h.StorageServiceHandler.NextAvailableDepartmentList(ctx, in, out)
}

func (h *storageServiceHandler) NextAvailableProviderList(ctx context.Context, in *NextAvailableProviderListRequest, out *AppointmentList) error {
	return h.StorageServiceHandler.NextAvailableProviderList(ctx, in, out)
}

func (h *storageServiceHandler) UpdateAppointmentType(ctx context.Context, in *UpdateAppointmentTypeRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.UpdateAppointmentType(ctx, in, out)
}

func (h *storageServiceHandler) GetProvider(ctx context.Context, in *ProviderRequest, out *Provider) error {
	return h.StorageServiceHandler.GetProvider(ctx, in, out)
}

func (h *storageServiceHandler) GetDepartment(ctx context.Context, in *DepartmentRequest, out *Department) error {
	return h.StorageServiceHandler.GetDepartment(ctx, in, out)
}

func (h *storageServiceHandler) SetDepartmentActiveState(ctx context.Context, in *DepartmentActiveStateRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetDepartmentActiveState(ctx, in, out)
}

func (h *storageServiceHandler) SetProviderActiveState(ctx context.Context, in *ProviderActiveStateRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetProviderActiveState(ctx, in, out)
}

func (h *storageServiceHandler) SetTenantCronJob(ctx context.Context, in *TenantCronJobRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetTenantCronJob(ctx, in, out)
}

func (h *storageServiceHandler) SetTenantCronJobStatus(ctx context.Context, in *TenantCronJobStatusRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetTenantCronJobStatus(ctx, in, out)
}

func (h *storageServiceHandler) GetTenantCronJob(ctx context.Context, in *Tenant, out *TenantCronJob) error {
	return h.StorageServiceHandler.GetTenantCronJob(ctx, in, out)
}

func (h *storageServiceHandler) GetProviderDepartmentsRange(ctx context.Context, in *ProviderDepartmentsRangeRequest, out *ProviderDepartmentsRangeResponse) error {
	return h.StorageServiceHandler.GetProviderDepartmentsRange(ctx, in, out)
}

func (h *storageServiceHandler) GetDepartmentProvidersRange(ctx context.Context, in *DepartmentProvidersRangeRequest, out *DepartmentProvidersRangeResponse) error {
	return h.StorageServiceHandler.GetDepartmentProvidersRange(ctx, in, out)
}

func (h *storageServiceHandler) SetProviderVisitType(ctx context.Context, in *ProviderVisitTypeRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.SetProviderVisitType(ctx, in, out)
}

func (h *storageServiceHandler) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, out *emptypb.Empty) error {
	return h.StorageServiceHandler.UpdateProvider(ctx, in, out)
}
