// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)
